package id.herbatech.erp.fin;

import id.herbatech.erp.shared.domain.DocumentEntity;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/** FIN-03 Jurnal umum (manual) atau jurnal otomatis dari dokumen sumber modul lain. */
@Getter
@Setter
@Entity
@Table(name = "journal_entry", schema = "fin")
public class JournalEntry extends DocumentEntity {

    private String description;
    private boolean autoGenerated;
    private String sourceDocType;
    private Long sourceDocId;
    private String sourceDocNo;
    private Long reversalOfId;
    private Long reversedById;
    private BigDecimal totalDebit = BigDecimal.ZERO;
    private BigDecimal totalCredit = BigDecimal.ZERO;

    @OneToMany(mappedBy = "entry", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("lineNo")
    private List<JournalLine> lines = new ArrayList<>();

    public void replaceLines(List<JournalLine> newLines) {
        lines.clear();
        short no = 1;
        for (JournalLine l : newLines) {
            l.setEntry(this);
            l.setLineNo(no++);
            lines.add(l);
        }
        recalc();
    }

    public void recalc() {
        totalDebit = lines.stream().map(JournalLine::getDebit).reduce(BigDecimal.ZERO, BigDecimal::add);
        totalCredit = lines.stream().map(JournalLine::getCredit).reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    public boolean isBalanced() {
        return totalDebit.compareTo(totalCredit) == 0 && totalDebit.signum() > 0;
    }
}
