package id.herbatech.erp.fin;

import id.herbatech.erp.shared.config.TimeService;
import id.herbatech.erp.shared.document.DocumentHandler;
import id.herbatech.erp.shared.document.NumberingService;
import id.herbatech.erp.shared.domain.DocStatus;
import id.herbatech.erp.shared.error.BusinessException;
import id.herbatech.erp.shared.error.NotFoundException;
import id.herbatech.erp.shared.security.UserContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Aturan dokumen Jurnal Umum (JV) untuk siklus status kernel.
 * PRD FIN aturan 3: jurnal otomatis tidak bisa diedit atau dibalik langsung — koreksi lewat dokumen sumber.
 */
@Component
class JournalHandler implements DocumentHandler<JournalEntry> {

    static final String DOC_TYPE = "JV";

    private final JournalEntryRepository repo;
    private final NumberingService numbering;
    private final TimeService time;
    private final JdbcTemplate jdbc;

    JournalHandler(JournalEntryRepository repo, NumberingService numbering, TimeService time, JdbcTemplate jdbc) {
        this.repo = repo;
        this.numbering = numbering;
        this.time = time;
        this.jdbc = jdbc;
    }

    @Override
    public String docType() {
        return DOC_TYPE;
    }

    @Override
    public String periodModule() {
        return "FIN";
    }

    @Override
    public JournalEntry load(Long id) {
        return repo.findWithLinesById(id).orElseThrow(() -> new NotFoundException("Jurnal", id));
    }

    @Override
    public JournalEntry save(JournalEntry doc) {
        return repo.save(doc);
    }

    @Override
    public String summary(JournalEntry doc) {
        return doc.getDescription();
    }

    @Override
    public BigDecimal amount(JournalEntry doc) {
        return doc.getTotalDebit();
    }

    @Override
    public void validateSubmit(JournalEntry doc) {
        if (doc.isAutoGenerated()) {
            throw new BusinessException("AUTO_JOURNAL", "Jurnal otomatis tidak melalui pengajuan");
        }
        validateLines(doc);
    }

    @Override
    public void onPost(JournalEntry doc) {
        validateLines(doc);
    }

    @Override
    public JournalEntry reverse(JournalEntry doc, LocalDate date, String reason) {
        if (doc.isAutoGenerated()) {
            throw new BusinessException("AUTO_JOURNAL",
                    "Jurnal otomatis dikoreksi dengan membatalkan dokumen sumber " + doc.getSourceDocNo() + " (PRD FIN aturan 3)");
        }
        return reversalOf(doc, date, "Reversal " + doc.getDocNo() + ": " + reason);
    }

    /** Membuat jurnal balik terposting (dipakai reversal manual dan reversal jurnal otomatis). */
    JournalEntry reversalOf(JournalEntry doc, LocalDate date, String description) {
        JournalEntry rev = new JournalEntry();
        rev.setPlantId(doc.getPlantId());
        rev.setDocDate(date);
        rev.setDocNo(numbering.next(DOC_TYPE, doc.getPlantId(), date));
        rev.setDescription(description.length() > 255 ? description.substring(0, 255) : description);
        rev.setAutoGenerated(doc.isAutoGenerated());
        rev.setSourceDocType(doc.getSourceDocType());
        rev.setSourceDocId(doc.getSourceDocId());
        rev.setSourceDocNo(doc.getSourceDocNo());
        rev.setReversalOfId(doc.getId());
        rev.replaceLines(doc.getLines().stream()
                .map(l -> JournalLine.of(l.getAccountId(), l.getCostCenterId(), l.getDescription(), l.getCredit(), l.getDebit()))
                .toList());
        rev.setStatus(DocStatus.POSTED);
        Long uid = UserContext.currentOptional().map(u -> u.id()).orElse(null);
        rev.setPostedBy(uid);
        rev.setPostedAt(time.now());
        JournalEntry saved = repo.save(rev);
        doc.setReversedById(saved.getId());
        return saved;
    }

    void validateLines(JournalEntry doc) {
        List<JournalLine> lines = doc.getLines();
        if (lines.size() < 2) {
            throw new BusinessException("JV_LINES", "Jurnal minimal dua baris");
        }
        doc.recalc();
        if (!doc.isBalanced()) {
            throw BusinessException.of("JV_BALANCE", "Jurnal tidak seimbang: debit %s, kredit %s",
                    doc.getTotalDebit().toPlainString(), doc.getTotalCredit().toPlainString());
        }
        Map<Long, Map<String, Object>> accounts = accounts(lines.stream().map(JournalLine::getAccountId).toList());
        for (JournalLine l : lines) {
            if (l.getDebit().signum() < 0 || l.getCredit().signum() < 0) {
                throw new BusinessException("JV_NEGATIVE", "Baris " + l.getLineNo() + ": nilai tidak boleh negatif");
            }
            if ((l.getDebit().signum() > 0) == (l.getCredit().signum() > 0)) {
                throw new BusinessException("JV_SIDE", "Baris " + l.getLineNo() + ": isi debit atau kredit, salah satu saja");
            }
            Map<String, Object> acc = accounts.get(l.getAccountId());
            if (acc == null) {
                throw new BusinessException("JV_ACCOUNT", "Baris " + l.getLineNo() + ": akun tidak ditemukan");
            }
            if (!(Boolean) acc.get("postable") || !(Boolean) acc.get("active")) {
                throw new BusinessException("JV_ACCOUNT", "Baris " + l.getLineNo() + ": akun " + acc.get("code")
                        + " adalah akun header atau tidak aktif");
            }
            if ((Boolean) acc.get("requires_cost_center") && l.getCostCenterId() == null) {
                throw new BusinessException("JV_CC", "Baris " + l.getLineNo() + ": akun " + acc.get("code") + " wajib cost center");
            }
        }
    }

    private Map<Long, Map<String, Object>> accounts(List<Long> ids) {
        List<Long> distinct = ids.stream().filter(id -> id != null).distinct().toList();
        if (distinct.isEmpty()) {
            return Map.of();
        }
        String in = distinct.stream().map(String::valueOf).collect(Collectors.joining(","));
        Map<Long, Map<String, Object>> out = new HashMap<>();
        jdbc.queryForList("SELECT id, code, postable, active, requires_cost_center FROM fin.account WHERE id IN (" + in + ")")
                .forEach(r -> out.put(((Number) r.get("id")).longValue(), r));
        return out;
    }
}
