package id.herbatech.erp.fin;

import id.herbatech.erp.shared.approval.OrgDirectory;
import id.herbatech.erp.shared.document.DocumentWorkflowService;
import id.herbatech.erp.shared.error.BusinessException;
import id.herbatech.erp.shared.security.Action;
import id.herbatech.erp.shared.security.CurrentUser;
import id.herbatech.erp.shared.security.PermissionService;
import id.herbatech.erp.shared.security.UserContext;
import id.herbatech.erp.shared.security.UserDirectory;
import id.herbatech.erp.shared.web.PageResponse;
import id.herbatech.erp.shared.web.Specs;
import jakarta.persistence.criteria.Predicate;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** FIN-03 Jurnal Umum & Jurnal Otomatis. */
@RestController
@RequestMapping("/api/fin/journals")
class JournalController {

    static final String MENU = "FIN-03";

    public record LineRequest(@NotNull Long accountId, Long costCenterId, @Size(max = 255) String description,
                              @PositiveOrZero BigDecimal debit, @PositiveOrZero BigDecimal credit) {
    }

    public record JournalRequest(@NotNull LocalDate docDate, @NotBlank @Size(max = 255) String description,
                                 @NotEmpty List<@Valid LineRequest> lines, Integer version) {
    }

    public record LineView(Long id, int lineNo, Long accountId, String accountCode, String accountName, Long costCenterId,
                           String costCenterCode, String description, BigDecimal debit, BigDecimal credit) {
    }

    public record JournalView(Long id, String docNo, LocalDate docDate, String status, String description,
                              boolean autoGenerated, String sourceDocType, Long sourceDocId, String sourceDocNo,
                              Long reversalOfId, String reversalOfNo, Long reversedById, String reversedByNo,
                              BigDecimal totalDebit, BigDecimal totalCredit, List<LineView> lines,
                              Long createdBy, String createdByName, Instant createdAt, Instant submittedAt,
                              Long approvedBy, String approvedByName, Instant approvedAt,
                              Long postedBy, String postedByName, Instant postedAt, String cancelReason,
                              Integer version, List<String> actions) {
    }

    public record JournalRow(Long id, String docNo, LocalDate docDate, String description, BigDecimal totalDebit,
                             String status, boolean autoGenerated, String sourceDocNo, String createdByName) {
    }

    private final JournalEntryRepository repo;
    private final JournalHandler handler;
    private final DocumentWorkflowService workflow;
    private final PermissionService perm;
    private final OrgDirectory org;
    private final UserDirectory users;
    private final JdbcTemplate jdbc;

    JournalController(JournalEntryRepository repo, JournalHandler handler, DocumentWorkflowService workflow,
                      PermissionService perm, OrgDirectory org, UserDirectory users, JdbcTemplate jdbc) {
        this.repo = repo;
        this.handler = handler;
        this.workflow = workflow;
        this.perm = perm;
        this.org = org;
        this.users = users;
        this.jdbc = jdbc;
    }

    @GetMapping
    @Transactional(readOnly = true)
    public PageResponse<JournalRow> list(@RequestParam Map<String, String> params) {
        perm.require(MENU, Action.VIEW);
        CurrentUser me = UserContext.current();
        Set<Long> visible = org.visibleCreatorIds(me.id(), perm.viewScope("FIN"));
        Specification<JournalEntry> base = Specs.fromParams(params, List.of("docNo", "description", "sourceDocNo"));
        Specification<JournalEntry> scoped = base.and((root, q, cb) -> {
            List<Predicate> ps = new ArrayList<>();
            ps.add(cb.equal(root.get("plantId"), me.plantId()));
            if (visible != null) {
                ps.add(root.get("createdBy").in(visible));
            }
            if (params.get("from") != null) {
                ps.add(cb.greaterThanOrEqualTo(root.get("docDate"), LocalDate.parse(params.get("from"))));
            }
            if (params.get("to") != null) {
                ps.add(cb.lessThanOrEqualTo(root.get("docDate"), LocalDate.parse(params.get("to"))));
            }
            return cb.and(ps.toArray(Predicate[]::new));
        });
        Page<JournalEntry> page = repo.findAll(scoped, Specs.pageable(params, Sort.by("docDate").descending(), JournalEntry.class));
        Map<Long, String> names = users.names(page.getContent().stream().map(JournalEntry::getCreatedBy).toList());
        return PageResponse.of(page, j -> new JournalRow(j.getId(), j.getDocNo(), j.getDocDate(), j.getDescription(),
                j.getTotalDebit(), j.getStatus().name(), j.isAutoGenerated(), j.getSourceDocNo(),
                j.getCreatedBy() == null ? "Sistem" : names.get(j.getCreatedBy())));
    }

    @GetMapping("/{id}")
    @Transactional(readOnly = true)
    public JournalView get(@PathVariable Long id) {
        perm.require(MENU, Action.VIEW);
        JournalEntry je = handler.load(id);
        assertVisible(je);
        return view(je);
    }

    @PostMapping
    @Transactional
    public JournalView create(@Valid @RequestBody JournalRequest req) {
        JournalEntry je = new JournalEntry();
        je.setDocDate(req.docDate());
        apply(je, req);
        JournalEntry saved = workflow.initDraft(handler, je);
        return view(saved);
    }

    @PutMapping("/{id}")
    @Transactional
    public JournalView update(@PathVariable Long id, @Valid @RequestBody JournalRequest req) {
        JournalEntry je = handler.load(id);
        if (je.isAutoGenerated()) {
            throw new BusinessException("AUTO_JOURNAL", "Jurnal otomatis tidak bisa diedit (PRD FIN aturan 3)");
        }
        if (req.version() != null && !req.version().equals(je.getVersion())) {
            throw new org.springframework.dao.OptimisticLockingFailureException("version");
        }
        je.setDocDate(req.docDate());
        workflow.assertEditable(handler, je);
        apply(je, req);
        JournalEntry saved = handler.save(je);
        workflow.touched(handler, saved);
        return view(saved);
    }

    private void apply(JournalEntry je, JournalRequest req) {
        je.setDescription(req.description().trim());
        je.replaceLines(req.lines().stream()
                .map(l -> JournalLine.of(l.accountId(), l.costCenterId(), l.description(), l.debit(), l.credit()))
                .toList());
    }

    private void assertVisible(JournalEntry je) {
        CurrentUser me = UserContext.current();
        Set<Long> visible = org.visibleCreatorIds(me.id(), perm.viewScope("FIN"));
        if (visible != null && !visible.contains(je.getCreatedBy()) && !je.isAutoGenerated()) {
            throw new org.springframework.security.access.AccessDeniedException("Dokumen ini di luar cakupan data Anda");
        }
    }

    JournalView view(JournalEntry je) {
        Map<Long, String[]> acc = new HashMap<>();
        Map<Long, String> cc = new HashMap<>();
        List<Long> accIds = je.getLines().stream().map(JournalLine::getAccountId).distinct().toList();
        List<Long> ccIds = je.getLines().stream().map(JournalLine::getCostCenterId).filter(x -> x != null).distinct().toList();
        if (!accIds.isEmpty()) {
            jdbc.query("SELECT id, code, name FROM fin.account WHERE id = ANY (?)",
                    rs -> {
                        acc.put(rs.getLong(1), new String[]{rs.getString(2), rs.getString(3)});
                    }, (Object) accIds.toArray(Long[]::new));
        }
        if (!ccIds.isEmpty()) {
            jdbc.query("SELECT id, code FROM sys.cost_center WHERE id = ANY (?)",
                    rs -> {
                        cc.put(rs.getLong(1), rs.getString(2));
                    }, (Object) ccIds.toArray(Long[]::new));
        }
        List<LineView> lines = je.getLines().stream().map(l -> {
            String[] a = acc.getOrDefault(l.getAccountId(), new String[]{"?", "?"});
            return new LineView(l.getId(), l.getLineNo(), l.getAccountId(), a[0], a[1], l.getCostCenterId(),
                    cc.get(l.getCostCenterId()), l.getDescription(), l.getDebit(), l.getCredit());
        }).toList();
        Map<Long, String> names = users.names(List.of(
                nz(je.getCreatedBy()), nz(je.getApprovedBy()), nz(je.getPostedBy())));
        String reversalOfNo = je.getReversalOfId() == null ? null : repo.findById(je.getReversalOfId()).map(JournalEntry::getDocNo).orElse(null);
        String reversedByNo = je.getReversedById() == null ? null : repo.findById(je.getReversedById()).map(JournalEntry::getDocNo).orElse(null);
        return new JournalView(je.getId(), je.getDocNo(), je.getDocDate(), je.getStatus().name(), je.getDescription(),
                je.isAutoGenerated(), je.getSourceDocType(), je.getSourceDocId(), je.getSourceDocNo(),
                je.getReversalOfId(), reversalOfNo, je.getReversedById(), reversedByNo,
                je.getTotalDebit(), je.getTotalCredit(), lines,
                je.getCreatedBy(), je.getCreatedBy() == null ? "Sistem" : names.get(je.getCreatedBy()), je.getCreatedAt(),
                je.getSubmittedAt(), je.getApprovedBy(), names.get(je.getApprovedBy()), je.getApprovedAt(),
                je.getPostedBy(), names.get(je.getPostedBy()), je.getPostedAt(), je.getCancelReason(),
                je.getVersion(), workflow.allowedActions(JournalHandler.DOC_TYPE, je));
    }

    private static Long nz(Long v) {
        return v == null ? -1L : v;
    }
}
