import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { keepPreviousData, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../api/client';
import type { Page } from '../../api/types';
import { DataTable, exportCsv, Pager } from '../../components/DataTable';
import { DocumentActions, DocumentSidePanel, useDocPanel } from '../../components/DocumentPanel';
import { Icon } from '../../components/icons';
import { LookupSelect } from '../../components/Lookup';
import { StatusChip } from '../../components/StatusChip';
import { errorText, Spinner, StatusPipeline, useDebounced, useToast } from '../../components/ui';
import { fmtDate, fmtDateTime, fmtNumber, fmtRp, todayIso } from '../../lib/format';
import { menuPath, useDocTypes } from '../../lib/meta';

const MENU = 'FIN-03';

interface JournalRow { id: number; docNo: string; docDate: string; description: string; totalDebit: number; status: string; autoGenerated: boolean; sourceDocNo: string | null; createdByName: string | null }
interface LineView { id?: number; accountId: number | null; costCenterId: number | null; description: string | null; debit: number; credit: number; accountCode?: string; accountName?: string; costCenterCode?: string | null }
interface JournalView {
  id: number; docNo: string; docDate: string; status: string; description: string; autoGenerated: boolean;
  sourceDocType: string | null; sourceDocId: number | null; sourceDocNo: string | null;
  reversalOfId: number | null; reversalOfNo: string | null; reversedById: number | null; reversedByNo: string | null;
  totalDebit: number; totalCredit: number; lines: LineView[];
  createdByName: string | null; createdAt: string; submittedAt: string | null; approvedByName: string | null; approvedAt: string | null;
  postedByName: string | null; postedAt: string | null; cancelReason: string | null; version: number; actions: string[];
}

const STATUS_FILTER = [['', 'Semua'], ['DRAFT', 'Draft'], ['SUBMITTED', 'Diajukan'], ['APPROVED', 'Disetujui'], ['POSTED', 'Diposting'], ['REJECTED', 'Ditolak'], ['CANCELLED', 'Dibatalkan']];

/** FIN-03 daftar jurnal. */
export function JournalList() {
  const nav = useNavigate();
  const toast = useToast();
  const [q, setQ] = useState('');
  const term = useDebounced(q, 300);
  const [status, setStatus] = useState('');
  const [auto, setAuto] = useState('');
  const [month, setMonth] = useState(todayIso().slice(0, 7));
  const [page, setPage] = useState(0);
  const [sort, setSort] = useState('-docDate');
  useEffect(() => setPage(0), [term, status, auto, month, sort]);
  const range = useMemo(() => {
    if (!month) return {};
    const [y, m] = month.split('-').map(Number);
    const last = new Date(y, m, 0).getDate();
    return { from: `${month}-01`, to: `${month}-${String(last).padStart(2, '0')}` };
  }, [month]);
  const params = { q: term, status, autoGenerated: auto, page, size: 50, sort, ...range };
  const query = useQuery({ queryKey: ['journals', params], queryFn: () => api.get<Page<JournalRow>>('/fin/journals', params), placeholderData: keepPreviousData });

  useEffect(() => {
    const h = (e: KeyboardEvent) => { if (e.altKey && e.key.toLowerCase() === 'n') { e.preventDefault(); nav(menuPath(MENU, 'new')); } };
    window.addEventListener('keydown', h);
    return () => window.removeEventListener('keydown', h);
  }, [nav]);

  const doExport = async () => {
    try {
      const all = await api.get<Page<JournalRow>>('/fin/journals', { ...params, page: 0, size: 10000 });
      exportCsv(`jurnal-${month || 'semua'}.csv`, ['No. Dokumen', 'Tanggal', 'Uraian', 'Nilai', 'Status', 'Otomatis', 'Dokumen sumber', 'Dibuat oleh'],
        all.content.map((r) => [r.docNo, fmtDate(r.docDate), r.description, r.totalDebit, r.status, r.autoGenerated ? 'Ya' : 'Tidak', r.sourceDocNo, r.createdByName]));
    } catch (e) { toast.error(e); }
  };

  return (
    <div className="card" style={{ overflow: 'hidden' }}>
      <div className="toolbar">
        <select className="input" style={{ width: 'auto', height: 32 }} value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Status">
          {STATUS_FILTER.map(([v, l]) => <option key={v} value={v}>Status: {l}</option>)}
        </select>
        <select className="input" style={{ width: 'auto', height: 32 }} value={auto} onChange={(e) => setAuto(e.target.value)} aria-label="Jenis jurnal">
          <option value="">Jenis: Semua</option><option value="false">Jurnal manual</option><option value="true">Jurnal otomatis</option>
        </select>
        <label className="row small muted">Periode <input className="input" type="month" style={{ width: 'auto', height: 32 }} value={month} onChange={(e) => setMonth(e.target.value)} /></label>
        <div style={{ flex: '1 1 200px', maxWidth: 320, marginLeft: 'auto' }}>
          <input className="input" style={{ height: 32 }} type="search" placeholder="Cari nomor atau uraian" aria-label="Cari" value={q} onChange={(e) => setQ(e.target.value)} />
        </div>
        <button className="btn" type="button" onClick={doExport}><Icon name="download" size={14} />Ekspor</button>
        <button className="btn btn-dark" type="button" title="Alt+N" onClick={() => nav(menuPath(MENU, 'new'))}><Icon name="plus" size={14} />Baru</button>
      </div>
      {query.error ? <div className="alert alert-err" style={{ margin: 12 }}>{errorText(query.error)}</div> : (
        <DataTable rows={query.data?.content ?? []} rowKey={(r) => r.id} onRowClick={(r) => nav(menuPath(MENU, r.id))} sort={sort} onSort={setSort}
          empty={query.isLoading ? 'Memuat…' : 'Belum ada jurnal di periode ini'}
          columns={[
            { key: 'docNo', label: 'No. Dokumen', mono: true, sortKey: 'docNo' },
            { key: 'docDate', label: 'Tanggal', mono: true, sortKey: 'docDate', render: (r) => fmtDate(r.docDate) },
            { key: 'description', label: 'Uraian', render: (r) => <>{r.description}{r.autoGenerated && <span className="mono small muted"> · otomatis dari {r.sourceDocNo}</span>}</> },
            { key: 'totalDebit', label: 'Nilai', align: 'right', sortKey: 'totalDebit', render: (r) => fmtRp(r.totalDebit) },
            { key: 'createdByName', label: 'Dibuat oleh', render: (r) => r.createdByName ?? 'Sistem' },
            { key: 'status', label: 'Status', render: (r) => <StatusChip status={r.status} /> },
          ]} />
      )}
      {query.data && <Pager page={page} totalPages={query.data.totalPages} total={query.data.totalElements} size={50} onPage={setPage} />}
    </div>
  );
}

const emptyLine = (): LineView => ({ accountId: null, costCenterId: null, description: '', debit: 0, credit: 0 });

/** FIN-03 formulir jurnal: header + pipeline status, tab baris & info, panel kanan. */
export function JournalForm() {
  const { id: idParam } = useParams();
  const isNew = idParam === 'new';
  const id = isNew ? undefined : Number(idParam);
  const nav = useNavigate();
  const qc = useQueryClient();
  const toast = useToast();
  const docTypes = useDocTypes();
  const doc = useQuery({ queryKey: ['journal', id], queryFn: () => api.get<JournalView>(`/fin/journals/${id}`), enabled: id != null });
  const panel = useDocPanel('JV', id);
  const [editing, setEditing] = useState(isNew);
  const [form, setForm] = useState<{ docDate: string; description: string; lines: LineView[] }>({ docDate: todayIso(), description: '', lines: [emptyLine(), emptyLine()] });
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [tab, setTab] = useState<'lines' | 'info'>('lines');

  useEffect(() => {
    if (doc.data && !editing) {
      setForm({ docDate: doc.data.docDate, description: doc.data.description, lines: doc.data.lines.map((l) => ({ ...l })) });
    }
  }, [doc.data, editing]);

  const totals = useMemo(() => form.lines.reduce((s, l) => ({ d: s.d + (Number(l.debit) || 0), c: s.c + (Number(l.credit) || 0) }), { d: 0, c: 0 }), [form.lines]);
  const balanced = Math.abs(totals.d - totals.c) < 0.005 && totals.d > 0;

  const save = async () => {
    setSaving(true);
    setErr(null);
    try {
      const body = {
        docDate: form.docDate, description: form.description, version: doc.data?.version,
        lines: form.lines.filter((l) => l.accountId != null).map((l) => ({ accountId: l.accountId, costCenterId: l.costCenterId, description: l.description || null, debit: Number(l.debit) || 0, credit: Number(l.credit) || 0 })),
      };
      const saved = isNew ? await api.post<JournalView>('/fin/journals', body) : await api.put<JournalView>(`/fin/journals/${id}`, body);
      toast.ok(isNew ? `Draft ${saved.docNo} dibuat` : 'Perubahan disimpan');
      setEditing(false);
      qc.setQueryData(['journal', saved.id], saved);
      qc.invalidateQueries({ queryKey: ['journals'] });
      qc.invalidateQueries({ queryKey: ['doc-panel', 'JV', saved.id] });
      if (isNew) nav(menuPath(MENU, saved.id), { replace: true });
    } catch (e) {
      setErr(errorText(e));
    } finally {
      setSaving(false);
    }
  };

  useEffect(() => {
    const h = (e: KeyboardEvent) => { if (e.altKey && e.key.toLowerCase() === 's' && editing) { e.preventDefault(); void save(); } };
    window.addEventListener('keydown', h);
    return () => window.removeEventListener('keydown', h);
  });

  if (!isNew && doc.isLoading) return <Spinner />;
  if (!isNew && doc.error) return <div className="alert alert-err">{errorText(doc.error)}</div>;
  const d = doc.data;
  const setLine = (i: number, patch: Partial<LineView>) => setForm((s) => ({ ...s, lines: s.lines.map((l, j) => j === i ? { ...l, ...patch } : l) }));

  const refresh = (reversalId?: number) => {
    qc.invalidateQueries({ queryKey: ['journal', id] });
    qc.invalidateQueries({ queryKey: ['journals'] });
    panel.refetch();
    if (reversalId && reversalId !== id) nav(menuPath(MENU, reversalId));
  };

  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 16, alignItems: 'flex-start' }}>
      <div style={{ flex: '999 1 620px', minWidth: 0, display: 'flex', flexDirection: 'column', gap: 16 }}>
        <div className="card">
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12, justifyContent: 'space-between', alignItems: 'center', padding: '14px 16px', borderBottom: '1px solid var(--line)' }}>
            <div>
              <div className="lbl">Jurnal Umum{d?.autoGenerated ? ' · otomatis' : ''}</div>
              <div className="mono" style={{ fontSize: 18, fontWeight: 500 }}>{d?.docNo ?? 'Draft baru'}</div>
            </div>
            <StatusPipeline status={d?.status ?? 'DRAFT'} />
          </div>
          <div className="row" style={{ padding: '10px 16px', borderBottom: '1px solid var(--line)' }}>
            {d ? <DocumentActions docType="JV" id={d.id} actions={d.actions} panel={panel.data} requiresEsign={docTypes.get('JV')?.requiresEsign}
              editing={editing} saving={saving} onSave={save} onEdit={() => setEditing(true)} onChanged={refresh} />
              : <button className="btn btn-dark" type="button" disabled={saving} onClick={save} title="Alt+S">Simpan draft</button>}
            {editing && !isNew && <button className="btn" type="button" onClick={() => setEditing(false)}>Batal ubah</button>}
            <span className="spacer" />
            <button className="btn" type="button" onClick={() => nav(menuPath(MENU))}>Kembali ke daftar</button>
          </div>
          {d?.autoGenerated && <div className="alert alert-info" style={{ margin: 12 }}>Jurnal otomatis dari <span className="mono">{d.sourceDocNo}</span>. Tidak bisa diedit; koreksi dilakukan dengan membatalkan dokumen sumber (PRD FIN aturan 3).</div>}
          {d?.status === 'REJECTED' && <div className="alert alert-err" style={{ margin: 12 }}>Dokumen ditolak. Perbaiki lalu ajukan kembali — alasan ada di riwayat aktivitas.</div>}
          {d?.cancelReason && <div className="alert alert-warn" style={{ margin: 12 }}>{d.cancelReason}</div>}
          {d?.reversalOfNo && <div className="alert alert-info" style={{ margin: 12 }}>Reversal atas <a href={menuPath(MENU, d.reversalOfId!)} onClick={(e) => { e.preventDefault(); nav(menuPath(MENU, d.reversalOfId!)); }} className="mono">{d.reversalOfNo}</a></div>}

          <div className="grid-form" style={{ padding: 16 }}>
            <label className="field"><span className="req">Tanggal</span>
              <input type="date" value={form.docDate} disabled={!editing} onChange={(e) => setForm((s) => ({ ...s, docDate: e.target.value }))} />
            </label>
            <label className="field" style={{ gridColumn: 'span 2' }}><span className="req">Uraian</span>
              <input value={form.description} disabled={!editing} maxLength={255} onChange={(e) => setForm((s) => ({ ...s, description: e.target.value }))} />
            </label>
          </div>

          <div className="tabs">
            <button type="button" className={tab === 'lines' ? 'on' : ''} onClick={() => setTab('lines')}>Baris jurnal</button>
            <button type="button" className={tab === 'info' ? 'on' : ''} onClick={() => setTab('info')}>Info dokumen</button>
          </div>
          {tab === 'lines' && (
            <div className="table-wrap">
              <table className="t">
                <thead><tr><th style={{ width: 34 }}>#</th><th style={{ minWidth: 240 }}>Akun</th><th style={{ minWidth: 180 }}>Cost center</th><th>Keterangan</th><th style={{ textAlign: 'right', width: 150 }}>Debit</th><th style={{ textAlign: 'right', width: 150 }}>Kredit</th>{editing && <th style={{ width: 40 }} />}</tr></thead>
                <tbody>
                  {form.lines.map((l, i) => (
                    <tr key={i}>
                      <td className="mono muted">{i + 1}</td>
                      {editing ? <>
                        <td><LookupSelect lookup="accounts" value={l.accountId} allowClear={false} onChange={(v) => setLine(i, { accountId: v })} /></td>
                        <td><LookupSelect lookup="cost-centers" value={l.costCenterId} placeholder="—" onChange={(v) => setLine(i, { costCenterId: v })} /></td>
                        <td><input className="input" value={l.description ?? ''} onChange={(e) => setLine(i, { description: e.target.value })} aria-label="Keterangan baris" /></td>
                        <td><input className="input" type="number" min="0" step="any" style={{ textAlign: 'right' }} value={l.debit || ''} aria-label="Debit"
                          onChange={(e) => setLine(i, { debit: Number(e.target.value) || 0, credit: Number(e.target.value) ? 0 : l.credit })} /></td>
                        <td><input className="input" type="number" min="0" step="any" style={{ textAlign: 'right' }} value={l.credit || ''} aria-label="Kredit"
                          onChange={(e) => setLine(i, { credit: Number(e.target.value) || 0, debit: Number(e.target.value) ? 0 : l.debit })} /></td>
                        <td><button className="iconbtn" type="button" aria-label="Hapus baris" disabled={form.lines.length <= 2}
                          onClick={() => setForm((s) => ({ ...s, lines: s.lines.filter((_, j) => j !== i) }))}><Icon name="trash" /></button></td>
                      </> : <>
                        <td><span className="mono small">{l.accountCode}</span> {l.accountName}</td>
                        <td className="mono small">{l.costCenterCode ?? ''}</td>
                        <td>{l.description}</td>
                        <td className="num mono">{l.debit ? fmtNumber(l.debit) : ''}</td>
                        <td className="num mono">{l.credit ? fmtNumber(l.credit) : ''}</td>
                      </>}
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr>
                    <td colSpan={4}>
                      {editing && <button className="btn btn-sm" type="button" onClick={() => setForm((s) => ({ ...s, lines: [...s.lines, emptyLine()] }))}><Icon name="plus" size={13} />Tambah baris</button>}
                      {!balanced && <span style={{ color: 'var(--danger)', marginLeft: 12, fontWeight: 500 }}>Belum seimbang · selisih {fmtRp(Math.abs(totals.d - totals.c))}</span>}
                    </td>
                    <td className="num mono">{fmtNumber(totals.d)}</td>
                    <td className="num mono">{fmtNumber(totals.c)}</td>
                    {editing && <td />}
                  </tr>
                </tfoot>
              </table>
            </div>
          )}
          {tab === 'info' && d && (
            <dl style={{ display: 'grid', gridTemplateColumns: '180px 1fr', gap: '8px 16px', padding: 16, margin: 0, fontSize: 13 }}>
              <dt className="muted">Dibuat</dt><dd style={{ margin: 0 }}>{d.createdByName} · {fmtDateTime(d.createdAt)}</dd>
              <dt className="muted">Diajukan</dt><dd style={{ margin: 0 }}>{fmtDateTime(d.submittedAt) || '–'}</dd>
              <dt className="muted">Disetujui</dt><dd style={{ margin: 0 }}>{d.approvedByName ? `${d.approvedByName} · ${fmtDateTime(d.approvedAt)}` : d.approvedAt ? fmtDateTime(d.approvedAt) : '–'}</dd>
              <dt className="muted">Diposting</dt><dd style={{ margin: 0 }}>{d.postedByName ? `${d.postedByName} · ${fmtDateTime(d.postedAt)}` : '–'}</dd>
              <dt className="muted">Dokumen sumber</dt><dd style={{ margin: 0 }} className="mono">{d.sourceDocNo ?? '–'}</dd>
              <dt className="muted">Reversal</dt><dd style={{ margin: 0 }} className="mono">{d.reversedByNo ?? '–'}</dd>
            </dl>
          )}
          {err && <div className="alert alert-err" style={{ margin: 12 }}>{err}</div>}
        </div>
      </div>
      <div style={{ flex: '1 1 320px', minWidth: 0, maxWidth: 420 }}>
        {d ? <DocumentSidePanel docType="JV" id={d.id} panel={panel.data} /> :
          <div className="card"><div className="empty small">Riwayat, approval, dan lampiran tersedia setelah draft disimpan.</div></div>}
      </div>
    </div>
  );
}
