-- =====================================================================
-- Pengaturan Sistem (SYS-01 .. SYS-15): master data bersama.
-- Setiap tabel master memakai kolom standar: id, version, created_*, updated_*.
-- =====================================================================

-- SYS-01 Perusahaan, Plant & Site
CREATE TABLE sys.company (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(16)  NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    npwp        VARCHAR(32),
    address     TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

CREATE TABLE sys.plant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT       NOT NULL REFERENCES sys.company(id),
    code        VARCHAR(8)   NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    address     TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

-- SYS-02 Struktur Organisasi, Departemen & Cost Center
CREATE TABLE sys.department (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(16)  NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    parent_id   BIGINT REFERENCES sys.department(id),
    app_code    VARCHAR(8),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

CREATE TABLE sys.cost_center (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(16)  NOT NULL UNIQUE,
    name           VARCHAR(128) NOT NULL,
    department_id  BIGINT       NOT NULL REFERENCES sys.department(id),
    plant_id       BIGINT REFERENCES sys.plant(id),
    production     BOOLEAN      NOT NULL DEFAULT FALSE,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    version        INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT
);

-- SYS-03 Pengguna, Peran & Hak Akses
CREATE TABLE sys.role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(32)  NOT NULL UNIQUE,
    name         VARCHAR(128) NOT NULL,
    description  TEXT,
    view_scope   VARCHAR(12)  NOT NULL,          -- OWN / SECTION / DEPARTMENT / ALL
    actions      VARCHAR(255) NOT NULL,          -- daftar aksi dipisah koma
    builtin      BOOLEAN      NOT NULL DEFAULT FALSE,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    version      INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ,
    updated_by   BIGINT
);

CREATE TABLE sys.app_user (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(64)  NOT NULL UNIQUE,
    password_hash        VARCHAR(100) NOT NULL,
    full_name            VARCHAR(128) NOT NULL,
    email                VARCHAR(128),
    employee_id          BIGINT,
    default_plant_id     BIGINT REFERENCES sys.plant(id),
    locale               VARCHAR(5)   NOT NULL DEFAULT 'id',
    theme                VARCHAR(8)   NOT NULL DEFAULT 'light',
    density              VARCHAR(12)  NOT NULL DEFAULT 'comfortable',
    start_page           VARCHAR(12)  NOT NULL DEFAULT 'launcher',
    notify_prefs         VARCHAR(255) NOT NULL DEFAULT 'approval,deadline,rejected,escalation',
    failed_attempts      INTEGER      NOT NULL DEFAULT 0,
    locked_until         TIMESTAMPTZ,
    last_login_at        TIMESTAMPTZ,
    password_changed_at  TIMESTAMPTZ,
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    version              INTEGER      NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT
);

-- Peran digabung dengan departemen (aplikasi) dan dibatasi plant. app_code '*' = semua aplikasi.
CREATE TABLE sys.user_role (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT     NOT NULL REFERENCES sys.app_user(id) ON DELETE CASCADE,
    role_id   BIGINT     NOT NULL REFERENCES sys.role(id),
    app_code  VARCHAR(8) NOT NULL,
    plant_id  BIGINT REFERENCES sys.plant(id),
    UNIQUE (user_id, role_id, app_code, plant_id)
);

-- Pengecualian per menu × aksi (menimpa aksi bawaan peran).
CREATE TABLE sys.role_menu_permission (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    BIGINT      NOT NULL REFERENCES sys.role(id) ON DELETE CASCADE,
    menu_code  VARCHAR(16) NOT NULL,
    action     VARCHAR(12) NOT NULL,
    allowed    BOOLEAN     NOT NULL,
    UNIQUE (role_id, menu_code, action)
);

-- SYS-05 Penomoran dokumen (jenis dokumen) — juga acuan matriks approval.
CREATE TABLE sys.doc_type (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(16)  NOT NULL UNIQUE,
    name            VARCHAR(128) NOT NULL,
    app_code        VARCHAR(8)   NOT NULL,
    menu_code       VARCHAR(16)  NOT NULL,
    prefix          VARCHAR(16)  NOT NULL,
    reset_period    VARCHAR(8)   NOT NULL DEFAULT 'MONTHLY',  -- MONTHLY / YEARLY / NEVER
    requires_esign  BOOLEAN      NOT NULL DEFAULT FALSE,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    version         INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT
);

-- SYS-04 Matriks approval
CREATE TABLE sys.approval_rule (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type_code     VARCHAR(16)   NOT NULL REFERENCES sys.doc_type(code),
    level             SMALLINT      NOT NULL CHECK (level BETWEEN 1 AND 5),
    min_amount        NUMERIC(19,2) NOT NULL DEFAULT 0,
    approver_type     VARCHAR(16)   NOT NULL,     -- DIRECT_SUPERIOR / ROLE / USER
    approver_role     VARCHAR(32),
    approver_app      VARCHAR(8),
    approver_user_id  BIGINT REFERENCES sys.app_user(id),
    plant_id          BIGINT REFERENCES sys.plant(id),
    label             VARCHAR(128)  NOT NULL,
    active            BOOLEAN       NOT NULL DEFAULT TRUE,
    version           INTEGER       NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by        BIGINT,
    updated_at        TIMESTAMPTZ,
    updated_by        BIGINT
);
CREATE INDEX ix_approval_rule_doc ON sys.approval_rule (doc_type_code, level);

-- SYS-07 Satuan & Konversi
CREATE TABLE sys.uom (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(12)  NOT NULL UNIQUE,
    name        VARCHAR(64)  NOT NULL,
    category    VARCHAR(16)  NOT NULL,           -- MASS / VOLUME / COUNT / LENGTH / TIME
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

-- SYS-06 Item Master
CREATE TABLE sys.item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(32)  NOT NULL UNIQUE,
    name             VARCHAR(160) NOT NULL,
    type             VARCHAR(4)   NOT NULL,      -- RM / PM / WIP / FG / SP / ATK / SVC
    uom_id           BIGINT       NOT NULL REFERENCES sys.uom(id),
    category         VARCHAR(64),
    lot_tracked      BOOLEAN      NOT NULL DEFAULT TRUE,
    shelf_life_days  INTEGER,
    storage_class    VARCHAR(16),                -- AMBIENT / COOL / COLD / B3
    halal_critical   BOOLEAN      NOT NULL DEFAULT FALSE,
    status           VARCHAR(12)  NOT NULL DEFAULT 'ACTIVE', -- DEVELOPMENT / ACTIVE / BLOCKED / OBSOLETE
    description      TEXT,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    version          INTEGER      NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT
);
CREATE INDEX ix_item_type ON sys.item (type, active);

CREATE TABLE sys.uom_conversion (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_uom_id  BIGINT        NOT NULL REFERENCES sys.uom(id),
    to_uom_id    BIGINT        NOT NULL REFERENCES sys.uom(id),
    factor       NUMERIC(19,8) NOT NULL CHECK (factor > 0),
    item_id      BIGINT REFERENCES sys.item(id),
    active       BOOLEAN       NOT NULL DEFAULT TRUE,
    version      INTEGER       NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ,
    updated_by   BIGINT
);

-- SYS-11 Mata uang & kurs
CREATE TABLE sys.currency (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(3)   NOT NULL UNIQUE,
    name        VARCHAR(64)  NOT NULL,
    symbol      VARCHAR(8),
    decimals    SMALLINT     NOT NULL DEFAULT 2,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

CREATE TABLE sys.exchange_rate (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code  VARCHAR(3)    NOT NULL REFERENCES sys.currency(code),
    rate_date      DATE          NOT NULL,
    rate           NUMERIC(19,8) NOT NULL CHECK (rate > 0),
    tax_rate       NUMERIC(19,8),
    active         BOOLEAN       NOT NULL DEFAULT TRUE,
    version        INTEGER       NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT,
    UNIQUE (currency_code, rate_date)
);

-- SYS-12 Kode pajak
CREATE TABLE sys.tax_code (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(16)  NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    type        VARCHAR(12)  NOT NULL,           -- PPN / PPH21 / PPH22 / PPH23 / PPH4_2
    rate        NUMERIC(7,4) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

-- SYS-08 Mitra bisnis
CREATE TABLE sys.partner (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(16)   NOT NULL UNIQUE,
    name               VARCHAR(160)  NOT NULL,
    type               VARCHAR(12)   NOT NULL,   -- SUPPLIER / CUSTOMER / BOTH / EXPEDITION
    npwp               VARCHAR(32),
    address            TEXT,
    city               VARCHAR(64),
    phone              VARCHAR(32),
    email              VARCHAR(128),
    currency_code      VARCHAR(3) REFERENCES sys.currency(code),
    payment_term_days  INTEGER       NOT NULL DEFAULT 30,
    credit_limit       NUMERIC(19,2),
    active             BOOLEAN       NOT NULL DEFAULT TRUE,
    version            INTEGER       NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by         BIGINT,
    updated_at         TIMESTAMPTZ,
    updated_by         BIGINT
);
CREATE INDEX ix_partner_type ON sys.partner (type, active);

-- SYS-09 Gudang, zona & lokasi bin
CREATE TABLE sys.warehouse (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(16)  NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    plant_id    BIGINT       NOT NULL REFERENCES sys.plant(id),
    type        VARCHAR(16)  NOT NULL,           -- RM / PM / FG / SP / GENERAL / TRANSIT
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

CREATE TABLE sys.location (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id   BIGINT       NOT NULL REFERENCES sys.warehouse(id),
    bin_code       VARCHAR(24)  NOT NULL,
    zone           VARCHAR(24),
    temp_class     VARCHAR(16)  NOT NULL DEFAULT 'AMBIENT',
    is_quarantine  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_b3          BOOLEAN      NOT NULL DEFAULT FALSE,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    version        INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT,
    UNIQUE (warehouse_id, bin_code)
);

-- SYS-10 Kalender kerja, hari libur & shift
CREATE TABLE sys.holiday (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id    BIGINT REFERENCES sys.plant(id),
    date        DATE         NOT NULL,
    name        VARCHAR(128) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);
CREATE INDEX ix_holiday_date ON sys.holiday (date);

CREATE TABLE sys.shift (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(8)   NOT NULL UNIQUE,
    name        VARCHAR(64)  NOT NULL,
    start_time  TIME         NOT NULL,
    end_time    TIME         NOT NULL,
    plant_id    BIGINT REFERENCES sys.plant(id),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

-- SYS-13 Integrasi & log API
CREATE TABLE sys.integration_log (
    id               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    system           VARCHAR(24)  NOT NULL,      -- HRIS / BSC / ODOO / ABSENSI / TIMBANGAN / WEBHOOK
    direction        VARCHAR(4)   NOT NULL,      -- IN / OUT
    endpoint         VARCHAR(255) NOT NULL,
    ref_doc          VARCHAR(64),
    status           VARCHAR(12)  NOT NULL,      -- PENDING / SUCCESS / FAILED
    http_status      INTEGER,
    request_body     TEXT,
    response_body    TEXT,
    error            TEXT,
    attempts         INTEGER      NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_attempt_at  TIMESTAMPTZ
);
CREATE INDEX ix_integration_status ON sys.integration_log (status, created_at DESC);

-- SYS-15 Template dokumen, notifikasi & email
CREATE TABLE sys.notification_template (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(48)  NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    channel     VARCHAR(8)   NOT NULL,           -- BELL / EMAIL / PRINT
    subject     VARCHAR(255),
    body        TEXT         NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

-- Pengaturan per aplikasi (gear "Pengaturan aplikasi" > Umum).
CREATE TABLE sys.app_setting (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code    VARCHAR(8)   NOT NULL,
    key         VARCHAR(64)  NOT NULL,
    value       TEXT,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,
    UNIQUE (app_code, key)
);
