-- =====================================================================
-- HC inti yang dibutuhkan sejak M0: posisi (dasar approval atasan langsung)
-- dan data karyawan. Modul HC lengkap menambah tabel di fase berikutnya.
-- =====================================================================

-- HC-02 Struktur organisasi & posisi
CREATE TABLE hc.position (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(24)  NOT NULL UNIQUE,
    title          VARCHAR(128) NOT NULL,
    department_id  BIGINT       NOT NULL REFERENCES sys.department(id),
    reports_to_id  BIGINT REFERENCES hc.position(id),
    grade          VARCHAR(8),
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    version        INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT
);

-- HC-03 Data karyawan
CREATE TABLE hc.employee (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik             VARCHAR(24)  NOT NULL UNIQUE,
    name            VARCHAR(128) NOT NULL,
    email           VARCHAR(128),
    phone           VARCHAR(32),
    position_id     BIGINT REFERENCES hc.position(id),
    department_id   BIGINT REFERENCES sys.department(id),
    cost_center_id  BIGINT REFERENCES sys.cost_center(id),
    plant_id        BIGINT REFERENCES sys.plant(id),
    join_date       DATE         NOT NULL,
    end_date        DATE,
    employment      VARCHAR(8)   NOT NULL DEFAULT 'PKWTT',   -- PKWT / PKWTT / OS
    status          VARCHAR(12)  NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE / RESIGNED / TERMINATED
    delegate_id     BIGINT REFERENCES hc.employee(id),       -- pengganti saat cuti (approval)
    delegate_until  DATE,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    version         INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT
);
CREATE INDEX ix_employee_position ON hc.employee (position_id) WHERE status = 'ACTIVE';

ALTER TABLE sys.app_user ADD CONSTRAINT fk_user_employee FOREIGN KEY (employee_id) REFERENCES hc.employee(id);
