-- =====================================================================
-- FIN inti: bagan akun, mapping jurnal otomatis, jurnal umum (FIN-02, FIN-03).
-- =====================================================================

-- FIN-02 Bagan akun
CREATE TABLE fin.account (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                  VARCHAR(16)  NOT NULL UNIQUE,
    name                  VARCHAR(160) NOT NULL,
    type                  VARCHAR(10)  NOT NULL,      -- ASSET / LIABILITY / EQUITY / REVENUE / EXPENSE
    normal_balance        VARCHAR(1)   NOT NULL,      -- D / C
    parent_id             BIGINT REFERENCES fin.account(id),
    postable              BOOLEAN      NOT NULL DEFAULT TRUE,
    requires_cost_center  BOOLEAN      NOT NULL DEFAULT FALSE,
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    version               INTEGER      NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            BIGINT,
    updated_at            TIMESTAMPTZ,
    updated_by            BIGINT
);

-- Mapping akun otomatis per jenis transaksi (FIN-99). Dipakai posting jurnal otomatis.
CREATE TABLE fin.account_mapping (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_type           VARCHAR(32)  NOT NULL UNIQUE,  -- mis. GR_RM, ISSUE_TO_WIP, FG_RECEIPT, PAYROLL
    name               VARCHAR(128) NOT NULL,
    debit_account_id   BIGINT       NOT NULL REFERENCES fin.account(id),
    credit_account_id  BIGINT       NOT NULL REFERENCES fin.account(id),
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    version            INTEGER      NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by         BIGINT,
    updated_at         TIMESTAMPTZ,
    updated_by         BIGINT
);

-- FIN-03 Jurnal umum & otomatis. Dokumen standar + referensi dokumen sumber & reversal.
CREATE TABLE fin.journal_entry (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no           VARCHAR(40)   NOT NULL UNIQUE,
    plant_id         BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date         DATE          NOT NULL,
    status           VARCHAR(12)   NOT NULL,
    description      VARCHAR(255)  NOT NULL,
    auto_generated   BOOLEAN       NOT NULL DEFAULT FALSE,
    source_doc_type  VARCHAR(16),
    source_doc_id    BIGINT,
    source_doc_no    VARCHAR(40),
    reversal_of_id   BIGINT REFERENCES fin.journal_entry(id),
    reversed_by_id   BIGINT REFERENCES fin.journal_entry(id),
    total_debit      NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_credit     NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at     TIMESTAMPTZ,
    approved_by      BIGINT,
    approved_at      TIMESTAMPTZ,
    posted_by        BIGINT,
    posted_at        TIMESTAMPTZ,
    cancelled_by     BIGINT,
    cancelled_at     TIMESTAMPTZ,
    cancel_reason    TEXT,
    version          INTEGER       NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT
);
CREATE INDEX ix_je_list ON fin.journal_entry (plant_id, status, doc_date DESC);
CREATE INDEX ix_je_source ON fin.journal_entry (source_doc_type, source_doc_id);

CREATE TABLE fin.journal_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id        BIGINT        NOT NULL REFERENCES fin.journal_entry(id) ON DELETE CASCADE,
    line_no         SMALLINT      NOT NULL,
    account_id      BIGINT        NOT NULL REFERENCES fin.account(id),
    cost_center_id  BIGINT REFERENCES sys.cost_center(id),
    description     VARCHAR(255),
    debit           NUMERIC(19,2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
    credit          NUMERIC(19,2) NOT NULL DEFAULT 0 CHECK (credit >= 0),
    CHECK (NOT (debit > 0 AND credit > 0))
);
CREATE INDEX ix_jl_entry ON fin.journal_line (entry_id);
CREATE INDEX ix_jl_account ON fin.journal_line (account_id);
