-- =====================================================================
-- Inventory engine (PRD §14): ITEM -> LOT -> STOCK_MOVE / STOCK_QUANT.
-- Semua departemen yang menyentuh barang menulis lewat satu layanan.
-- =====================================================================

CREATE TABLE scm.lot (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_no        VARCHAR(40)  NOT NULL,
    item_id       BIGINT       NOT NULL REFERENCES sys.item(id),
    supplier_lot  VARCHAR(64),
    mfg_date      DATE,
    exp_date      DATE,
    qc_status     VARCHAR(12)  NOT NULL DEFAULT 'QUARANTINE', -- QUARANTINE / RELEASED / REJECTED / HOLD
    source_doc    VARCHAR(40),
    version       INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ,
    updated_by    BIGINT,
    UNIQUE (item_id, lot_no)
);
CREATE INDEX ix_lot_fefo ON scm.lot (item_id, qc_status, exp_date);

-- Saldo per item x lot x lokasi bin. Tidak boleh negatif.
CREATE TABLE scm.stock_quant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id       BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id        BIGINT REFERENCES scm.lot(id),
    location_id   BIGINT        NOT NULL REFERENCES sys.location(id),
    qty           NUMERIC(19,6) NOT NULL DEFAULT 0 CHECK (qty >= 0),
    qty_reserved  NUMERIC(19,6) NOT NULL DEFAULT 0 CHECK (qty_reserved >= 0),
    unit_cost     NUMERIC(19,6) NOT NULL DEFAULT 0,
    version       INTEGER       NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CHECK (qty_reserved <= qty)
);
CREATE UNIQUE INDEX ux_quant ON scm.stock_quant (item_id, COALESCE(lot_id, 0), location_id);
CREATE INDEX ix_quant_location ON scm.stock_quant (location_id);

-- Semua gerak barang. Append-only: koreksi dengan gerak balik.
CREATE TABLE scm.stock_move (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    move_type      VARCHAR(16)   NOT NULL,  -- RECEIPT / ISSUE / TRANSFER / PRODUCE / CONSUME / SHIP / ADJUST / RETURN / SCRAP
    item_id        BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id         BIGINT REFERENCES scm.lot(id),
    from_loc_id    BIGINT REFERENCES sys.location(id),
    to_loc_id      BIGINT REFERENCES sys.location(id),
    qty            NUMERIC(19,6) NOT NULL CHECK (qty > 0),
    unit_cost      NUMERIC(19,6) NOT NULL DEFAULT 0,
    move_date      DATE          NOT NULL,
    ref_doc_type   VARCHAR(16)   NOT NULL,
    ref_doc_id     BIGINT        NOT NULL,
    ref_doc_no     VARCHAR(40)   NOT NULL,
    reason         TEXT,
    user_id        BIGINT,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CHECK (from_loc_id IS NOT NULL OR to_loc_id IS NOT NULL)
);
CREATE INDEX ix_move_lot ON scm.stock_move (lot_id, created_at);
CREATE INDEX ix_move_item ON scm.stock_move (item_id, move_date);
CREATE INDEX ix_move_ref ON scm.stock_move (ref_doc_type, ref_doc_id);
CREATE TRIGGER trg_stock_move_immutable BEFORE UPDATE OR DELETE ON scm.stock_move
    FOR EACH ROW EXECUTE FUNCTION core.forbid_change();
