-- =====================================================================
-- M1 · HRD / Human Capital: absensi, cuti/lembur/SPD, payroll, BPJS, PPh 21,
-- kualifikasi operator, kontrak, pinjaman, on/offboarding, SARMUT.
-- =====================================================================

-- Infrastruktur kernel tambahan
ALTER TABLE sys.doc_type ADD COLUMN ess_menu_code VARCHAR(16);
ALTER TABLE sys.approval_rule ADD COLUMN condition_key VARCHAR(32);

-- HC-03: data karyawan untuk payroll & pajak
ALTER TABLE hc.employee
    ADD COLUMN ktp_no           VARCHAR(20),
    ADD COLUMN npwp             VARCHAR(32),
    ADD COLUMN ptkp_status      VARCHAR(5)  NOT NULL DEFAULT 'TK/0',
    ADD COLUMN birth_date       DATE,
    ADD COLUMN gender           VARCHAR(1),
    ADD COLUMN address          TEXT,
    ADD COLUMN bank_name        VARCHAR(64),
    ADD COLUMN bank_account_no  VARCHAR(32),
    ADD COLUMN bank_account_name VARCHAR(128),
    ADD COLUMN bpjs_kes_no      VARCHAR(32),
    ADD COLUMN bpjs_tk_no       VARCHAR(32),
    ADD COLUMN default_shift_id BIGINT REFERENCES sys.shift(id);

-- ---------------------------------------------------------------- HC-08 Cuti & izin
CREATE TABLE hc.leave_type (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(16)  NOT NULL UNIQUE,
    name                 VARCHAR(128) NOT NULL,
    attendance_status    VARCHAR(8)   NOT NULL,     -- CUTI / IZIN / SAKIT / DINAS
    paid                 BOOLEAN      NOT NULL DEFAULT TRUE,
    deducts_annual       BOOLEAN      NOT NULL DEFAULT FALSE,
    max_days             INTEGER,
    requires_attachment  BOOLEAN      NOT NULL DEFAULT FALSE,
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    version              INTEGER      NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT
);

-- Hak cuti tahunan per karyawan per tahun (bawaan 12 hari bila tidak ada baris).
CREATE TABLE hc.leave_entitlement (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  BIGINT       NOT NULL REFERENCES hc.employee(id),
    year         SMALLINT     NOT NULL,
    days         NUMERIC(5,1) NOT NULL,
    carried_over NUMERIC(5,1) NOT NULL DEFAULT 0,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    version      INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ,
    updated_by   BIGINT,
    UNIQUE (employee_id, year)
);

CREATE TABLE hc.leave_request (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no           VARCHAR(40)  NOT NULL UNIQUE,
    plant_id         BIGINT       NOT NULL REFERENCES sys.plant(id),
    doc_date         DATE         NOT NULL,
    status           VARCHAR(12)  NOT NULL,
    employee_id      BIGINT       NOT NULL REFERENCES hc.employee(id),
    leave_type_id    BIGINT       NOT NULL REFERENCES hc.leave_type(id),
    start_date       DATE         NOT NULL,
    end_date         DATE         NOT NULL,
    days             NUMERIC(5,1) NOT NULL DEFAULT 0,
    reason           TEXT,
    delegate_employee_id BIGINT REFERENCES hc.employee(id),
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT,
    CHECK (end_date >= start_date)
);
CREATE INDEX ix_leave_emp ON hc.leave_request (employee_id, start_date);

-- ---------------------------------------------------------------- HC-08 Lembur (satu dokumen bisa banyak karyawan)
CREATE TABLE hc.overtime_request (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no       VARCHAR(40)  NOT NULL UNIQUE,
    plant_id     BIGINT       NOT NULL REFERENCES sys.plant(id),
    doc_date     DATE         NOT NULL,
    status       VARCHAR(12)  NOT NULL,
    work_date    DATE         NOT NULL,
    day_type     VARCHAR(8)   NOT NULL DEFAULT 'WORKDAY',   -- WORKDAY / RESTDAY / HOLIDAY
    reason       TEXT         NOT NULL,
    reference    VARCHAR(64),
    total_hours  NUMERIC(7,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE TABLE hc.overtime_line (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id   BIGINT       NOT NULL REFERENCES hc.overtime_request(id) ON DELETE CASCADE,
    line_no      SMALLINT     NOT NULL,
    employee_id  BIGINT       NOT NULL REFERENCES hc.employee(id),
    start_time   TIME         NOT NULL,
    end_time     TIME         NOT NULL,
    hours        NUMERIC(5,2) NOT NULL CHECK (hours > 0),
    actual_hours NUMERIC(5,2)
);
CREATE INDEX ix_ot_line_emp ON hc.overtime_line (employee_id);

-- ---------------------------------------------------------------- HC-08 Perjalanan dinas (SPD)
CREATE TABLE hc.business_trip (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    employee_id     BIGINT        NOT NULL REFERENCES hc.employee(id),
    destination     VARCHAR(128)  NOT NULL,
    purpose         TEXT          NOT NULL,
    start_date      DATE          NOT NULL,
    end_date        DATE          NOT NULL,
    transport       VARCHAR(8)    NOT NULL DEFAULT 'DARAT',  -- DARAT / UDARA / LAUT
    abroad          BOOLEAN       NOT NULL DEFAULT FALSE,
    per_diem        NUMERIC(19,2) NOT NULL DEFAULT 0,
    advance_amount  NUMERIC(19,2) NOT NULL DEFAULT 0,
    cost_center_id  BIGINT REFERENCES sys.cost_center(id),
    advance_doc_no  VARCHAR(40),
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT,
    CHECK (end_date >= start_date)
);

-- ---------------------------------------------------------------- HC-07 Absensi & jadwal shift
CREATE TABLE hc.attendance (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT       NOT NULL REFERENCES hc.employee(id),
    work_date     DATE         NOT NULL,
    shift_id      BIGINT REFERENCES sys.shift(id),
    check_in      TIME,
    check_out     TIME,
    status        VARCHAR(8)   NOT NULL,      -- HADIR / IZIN / SAKIT / CUTI / ALPA / LIBUR / DINAS
    work_hours    NUMERIC(5,2) NOT NULL DEFAULT 0,
    late_minutes  INTEGER      NOT NULL DEFAULT 0,
    source        VARCHAR(8)   NOT NULL DEFAULT 'MANUAL',   -- MANUAL / MESIN / CUTI / SPD
    source_doc    VARCHAR(40),
    note          TEXT,
    version       INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ,
    updated_by    BIGINT,
    UNIQUE (employee_id, work_date)
);
CREATE INDEX ix_att_date ON hc.attendance (work_date);

-- ---------------------------------------------------------------- HC-09/10 Payroll
CREATE TABLE hc.salary_component (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(16)  NOT NULL UNIQUE,
    name          VARCHAR(128) NOT NULL,
    kind          VARCHAR(10)  NOT NULL,      -- EARNING / DEDUCTION / EMPLOYER
    fixed         BOOLEAN      NOT NULL DEFAULT TRUE,   -- tunjangan tetap (dasar upah lembur & BPJS)
    taxable       BOOLEAN      NOT NULL DEFAULT TRUE,
    account_code  VARCHAR(16)  NOT NULL,
    seq           SMALLINT     NOT NULL DEFAULT 100,
    system        BOOLEAN      NOT NULL DEFAULT FALSE,  -- dihitung sistem (lembur, BPJS, PPh 21, pinjaman)
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    version       INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ,
    updated_by    BIGINT
);

-- Gaji per karyawan per komponen (data rahasia: hanya peran Payroll & Direktur).
CREATE TABLE hc.employee_salary (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT        NOT NULL REFERENCES hc.employee(id),
    component_id  BIGINT        NOT NULL REFERENCES hc.salary_component(id),
    amount        NUMERIC(19,2) NOT NULL CHECK (amount >= 0),
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    version       INTEGER       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ,
    updated_by    BIGINT,
    UNIQUE (employee_id, component_id)
);

-- Parameter payroll (tarif BPJS, batas upah, pembagi lembur). Diperbarui tiap ada ketentuan baru.
CREATE TABLE hc.payroll_param (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key          VARCHAR(32)  NOT NULL UNIQUE,
    value        VARCHAR(64)  NOT NULL,
    description  TEXT,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    version      INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ,
    updated_by   BIGINT
);

-- PTKP tahunan per status (UU HPP).
CREATE TABLE hc.ptkp (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status     VARCHAR(5)    NOT NULL UNIQUE,
    amount     NUMERIC(19,2) NOT NULL,
    ter_category VARCHAR(1)  NOT NULL,
    active     BOOLEAN       NOT NULL DEFAULT TRUE,
    version    INTEGER       NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT
);

-- Tarif efektif rata-rata (TER) PPh 21 bulanan, PMK 168/2023. Batas atas inklusif; NULL = tanpa batas.
CREATE TABLE hc.pph21_ter (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category    VARCHAR(1)    NOT NULL,
    upper_limit NUMERIC(19,2),
    rate        NUMERIC(7,4)  NOT NULL,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    version     INTEGER       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);
CREATE INDEX ix_ter ON hc.pph21_ter (category, upper_limit);

CREATE TABLE hc.payroll_run (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no           VARCHAR(40)   NOT NULL UNIQUE,
    plant_id         BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date         DATE          NOT NULL,
    status           VARCHAR(12)   NOT NULL,
    period           VARCHAR(6)    NOT NULL,           -- YYYYMM
    description      VARCHAR(255),
    employee_count   INTEGER       NOT NULL DEFAULT 0,
    total_gross      NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_deduction  NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_net        NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_employer   NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_pph21      NUMERIC(19,2) NOT NULL DEFAULT 0,
    calculated_at    TIMESTAMPTZ,
    warnings         TEXT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE UNIQUE INDEX ux_payroll_period ON hc.payroll_run (plant_id, period) WHERE status NOT IN ('CANCELLED');

-- Slip per karyawan (ringkasan) dan baris komponen.
CREATE TABLE hc.payroll_slip (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           BIGINT        NOT NULL REFERENCES hc.payroll_run(id) ON DELETE CASCADE,
    employee_id      BIGINT        NOT NULL REFERENCES hc.employee(id),
    cost_center_id   BIGINT REFERENCES sys.cost_center(id),
    ptkp_status      VARCHAR(5)    NOT NULL,
    ter_category     VARCHAR(1)    NOT NULL,
    ter_rate         NUMERIC(7,4)  NOT NULL DEFAULT 0,
    work_days        INTEGER       NOT NULL DEFAULT 0,
    present_days     INTEGER       NOT NULL DEFAULT 0,
    absent_days      INTEGER       NOT NULL DEFAULT 0,
    overtime_hours   NUMERIC(7,2)  NOT NULL DEFAULT 0,
    gross            NUMERIC(19,2) NOT NULL DEFAULT 0,
    taxable_gross    NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_deduction  NUMERIC(19,2) NOT NULL DEFAULT 0,
    net              NUMERIC(19,2) NOT NULL DEFAULT 0,
    employer_cost    NUMERIC(19,2) NOT NULL DEFAULT 0,
    pph21            NUMERIC(19,2) NOT NULL DEFAULT 0,
    UNIQUE (run_id, employee_id)
);
CREATE TABLE hc.payroll_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slip_id         BIGINT        NOT NULL REFERENCES hc.payroll_slip(id) ON DELETE CASCADE,
    component_code  VARCHAR(16)   NOT NULL,
    component_name  VARCHAR(128)  NOT NULL,
    kind            VARCHAR(10)   NOT NULL,
    account_code    VARCHAR(16)   NOT NULL,
    quantity        NUMERIC(9,2),
    amount          NUMERIC(19,2) NOT NULL,
    seq             SMALLINT      NOT NULL DEFAULT 100
);
CREATE INDEX ix_payroll_line_slip ON hc.payroll_line (slip_id);

-- ---------------------------------------------------------------- HC-14 Pinjaman & kasbon
CREATE TABLE hc.employee_loan (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no              VARCHAR(40)   NOT NULL UNIQUE,
    plant_id            BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date            DATE          NOT NULL,
    status              VARCHAR(12)   NOT NULL,
    employee_id         BIGINT        NOT NULL REFERENCES hc.employee(id),
    kind                VARCHAR(8)    NOT NULL DEFAULT 'PINJAMAN',   -- PINJAMAN / KASBON
    principal           NUMERIC(19,2) NOT NULL CHECK (principal > 0),
    installments        INTEGER       NOT NULL CHECK (installments BETWEEN 1 AND 60),
    installment_amount  NUMERIC(19,2) NOT NULL DEFAULT 0,
    start_period        VARCHAR(6)    NOT NULL,
    repaid_amount       NUMERIC(19,2) NOT NULL DEFAULT 0,
    purpose             TEXT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE TABLE hc.loan_repayment (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id   BIGINT        NOT NULL REFERENCES hc.employee_loan(id),
    slip_id   BIGINT        NOT NULL REFERENCES hc.payroll_slip(id) ON DELETE CASCADE,
    amount    NUMERIC(19,2) NOT NULL
);

-- ---------------------------------------------------------------- HC-12 Kualifikasi operator
CREATE TABLE hc.qualification (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT       NOT NULL REFERENCES hc.employee(id),
    process_code  VARCHAR(24)  NOT NULL,     -- mis. DISPENSING, GRANULASI, FILLING, PENGEMASAN
    line_id       BIGINT,
    valid_from    DATE         NOT NULL,
    valid_until   DATE         NOT NULL,
    basis         VARCHAR(16)  NOT NULL DEFAULT 'ASESMEN',   -- TRAINING / ASESMEN / SERTIFIKASI
    note          TEXT,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    version       INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ,
    updated_by    BIGINT
);
CREATE INDEX ix_qual_emp ON hc.qualification (employee_id, process_code, valid_until);

-- ---------------------------------------------------------------- HC-06 Kontrak
CREATE TABLE hc.employment_contract (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT       NOT NULL REFERENCES hc.employee(id),
    contract_no   VARCHAR(40)  NOT NULL UNIQUE,
    type          VARCHAR(8)   NOT NULL,     -- PKWT / PKWTT / OS / MAGANG
    start_date    DATE         NOT NULL,
    end_date      DATE,
    position_id   BIGINT REFERENCES hc.position(id),
    note          TEXT,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    version       INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ,
    updated_by    BIGINT
);

-- ---------------------------------------------------------------- HC-05 On/offboarding
CREATE TABLE hc.onboarding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)  NOT NULL UNIQUE,
    plant_id        BIGINT       NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE         NOT NULL,
    status          VARCHAR(12)  NOT NULL,
    employee_id     BIGINT       NOT NULL REFERENCES hc.employee(id),
    kind            VARCHAR(8)   NOT NULL,      -- ONBOARD / OFFBOARD
    effective_date  DATE         NOT NULL,
    reason          TEXT,
    applied         BOOLEAN      NOT NULL DEFAULT FALSE,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE TABLE hc.onboarding_task (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    onboarding_id  BIGINT       NOT NULL REFERENCES hc.onboarding(id) ON DELETE CASCADE,
    seq            SMALLINT     NOT NULL,
    code           VARCHAR(24)  NOT NULL,
    label          VARCHAR(160) NOT NULL,
    owner_app      VARCHAR(8)   NOT NULL,
    done           BOOLEAN      NOT NULL DEFAULT FALSE,
    done_by        BIGINT,
    done_at        TIMESTAMPTZ,
    note           TEXT
);

-- ---------------------------------------------------------------- HC-13 SARMUT
CREATE TABLE hc.sarmut_kpi (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(24)   NOT NULL UNIQUE,
    name         VARCHAR(160)  NOT NULL,
    app_code     VARCHAR(8)    NOT NULL,
    unit         VARCHAR(16)   NOT NULL,       -- %, hari, jam, kali
    direction    VARCHAR(6)    NOT NULL,       -- HIGHER / LOWER
    target       NUMERIC(19,4) NOT NULL,
    weight       NUMERIC(7,2)  NOT NULL DEFAULT 1,
    source       VARCHAR(6)    NOT NULL,       -- AUTO / MANUAL
    auto_key     VARCHAR(48),
    formula      TEXT,
    active       BOOLEAN       NOT NULL DEFAULT TRUE,
    version      INTEGER       NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ,
    updated_by   BIGINT
);
CREATE TABLE hc.sarmut_value (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_id       BIGINT        NOT NULL REFERENCES hc.sarmut_kpi(id),
    plant_id     BIGINT        NOT NULL REFERENCES sys.plant(id),
    period       VARCHAR(6)    NOT NULL,
    actual       NUMERIC(19,4),
    target       NUMERIC(19,4) NOT NULL,
    score        NUMERIC(7,2),
    source       VARCHAR(8)    NOT NULL,       -- AUTO / MANUAL
    source_doc   VARCHAR(40),
    note         TEXT,
    calculated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    sent_to_bsc_at TIMESTAMPTZ,
    UNIQUE (kpi_id, plant_id, period)
);
-- Input SARMUT manual wajib bukti & approval (PRD HC aturan 6).
CREATE TABLE hc.sarmut_input (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no      VARCHAR(40)  NOT NULL UNIQUE,
    plant_id    BIGINT       NOT NULL REFERENCES sys.plant(id),
    doc_date    DATE         NOT NULL,
    status      VARCHAR(12)  NOT NULL,
    period      VARCHAR(6)   NOT NULL,
    kpi_id      BIGINT       NOT NULL REFERENCES hc.sarmut_kpi(id),
    actual      NUMERIC(19,4) NOT NULL,
    evidence    TEXT         NOT NULL,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
