-- =====================================================================
-- M1 · Finance & Tax: hutang, piutang, kas & bank, aset tetap, anggaran.
-- Semua dokumen memakai kolom standar dokumen (PRD §14).
-- =====================================================================

-- Parameter FIN (FIN-99): tarif PPN, toleransi, aturan kredit & anggaran.
CREATE TABLE fin.fin_param (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key         VARCHAR(32)  NOT NULL UNIQUE,
    value       VARCHAR(64)  NOT NULL,
    description TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

-- FIN-99 Rekening bank & kas
CREATE TABLE fin.bank_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(16)  NOT NULL UNIQUE,
    name            VARCHAR(128) NOT NULL,
    kind            VARCHAR(6)   NOT NULL,      -- BANK / KAS
    bank_name       VARCHAR(64),
    account_no      VARCHAR(40),
    currency_code   VARCHAR(3)   NOT NULL DEFAULT 'IDR',
    gl_account_id   BIGINT       NOT NULL REFERENCES fin.account(id),
    plant_id        BIGINT REFERENCES sys.plant(id),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    version         INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT
);

-- ---------------------------------------------------------------- FIN-10 Faktur supplier
CREATE TABLE fin.ap_invoice (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no              VARCHAR(40)   NOT NULL UNIQUE,
    plant_id            BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date            DATE          NOT NULL,
    status              VARCHAR(12)   NOT NULL,
    partner_id          BIGINT        NOT NULL REFERENCES sys.partner(id),
    supplier_invoice_no VARCHAR(64)   NOT NULL,
    tax_invoice_no      VARCHAR(32),
    due_date            DATE          NOT NULL,
    description         VARCHAR(255),
    source_type         VARCHAR(8)    NOT NULL DEFAULT 'NON_PO',   -- NON_PO / PO (3-way match M2)
    with_ppn            BOOLEAN       NOT NULL DEFAULT TRUE,
    pph_tax_code        VARCHAR(16),
    subtotal            NUMERIC(19,2) NOT NULL DEFAULT 0,
    ppn_amount          NUMERIC(19,2) NOT NULL DEFAULT 0,
    pph_amount          NUMERIC(19,2) NOT NULL DEFAULT 0,
    total               NUMERIC(19,2) NOT NULL DEFAULT 0,
    payable             NUMERIC(19,2) NOT NULL DEFAULT 0,
    advance_payment_id  BIGINT,
    advance_applied     NUMERIC(19,2) NOT NULL DEFAULT 0,
    paid_amount         NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE UNIQUE INDEX ux_ap_supplier_inv ON fin.ap_invoice (partner_id, supplier_invoice_no) WHERE status <> 'CANCELLED';
CREATE INDEX ix_ap_due ON fin.ap_invoice (status, due_date);
CREATE TABLE fin.ap_invoice_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT        NOT NULL REFERENCES fin.ap_invoice(id) ON DELETE CASCADE,
    line_no         SMALLINT      NOT NULL,
    account_id      BIGINT        NOT NULL REFERENCES fin.account(id),
    cost_center_id  BIGINT REFERENCES sys.cost_center(id),
    description     VARCHAR(255),
    qty             NUMERIC(19,4) NOT NULL DEFAULT 1,
    unit_price      NUMERIC(19,4) NOT NULL DEFAULT 0,
    amount          NUMERIC(19,2) NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------- FIN-11/12 Pembayaran hutang & uang muka
CREATE TABLE fin.payment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no           VARCHAR(40)   NOT NULL UNIQUE,
    plant_id         BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date         DATE          NOT NULL,
    status           VARCHAR(12)   NOT NULL,
    kind             VARCHAR(8)    NOT NULL DEFAULT 'AP',      -- AP / ADVANCE
    partner_id       BIGINT        NOT NULL REFERENCES sys.partner(id),
    bank_account_id  BIGINT        NOT NULL REFERENCES fin.bank_account(id),
    method           VARCHAR(8)    NOT NULL DEFAULT 'TRANSFER',
    reference        VARCHAR(64),
    description      VARCHAR(255),
    amount           NUMERIC(19,2) NOT NULL DEFAULT 0,
    advance_used     NUMERIC(19,2) NOT NULL DEFAULT 0,
    reconciled       BOOLEAN       NOT NULL DEFAULT FALSE,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE TABLE fin.payment_allocation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id  BIGINT        NOT NULL REFERENCES fin.payment(id) ON DELETE CASCADE,
    line_no     SMALLINT      NOT NULL,
    invoice_id  BIGINT        NOT NULL REFERENCES fin.ap_invoice(id),
    amount      NUMERIC(19,2) NOT NULL CHECK (amount > 0)
);
ALTER TABLE fin.ap_invoice ADD CONSTRAINT fk_ap_advance FOREIGN KEY (advance_payment_id) REFERENCES fin.payment(id);

-- ---------------------------------------------------------------- FIN-20 Faktur penjualan
CREATE TABLE fin.ar_invoice (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no           VARCHAR(40)   NOT NULL UNIQUE,
    plant_id         BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date         DATE          NOT NULL,
    status           VARCHAR(12)   NOT NULL,
    partner_id       BIGINT        NOT NULL REFERENCES sys.partner(id),
    due_date         DATE          NOT NULL,
    tax_invoice_no   VARCHAR(32),
    customer_po      VARCHAR(64),
    description      VARCHAR(255),
    with_ppn         BOOLEAN       NOT NULL DEFAULT TRUE,
    subtotal         NUMERIC(19,2) NOT NULL DEFAULT 0,
    ppn_amount       NUMERIC(19,2) NOT NULL DEFAULT 0,
    total            NUMERIC(19,2) NOT NULL DEFAULT 0,
    received_amount  NUMERIC(19,2) NOT NULL DEFAULT 0,
    credit_hold      BOOLEAN       NOT NULL DEFAULT FALSE,
    hold_reason      TEXT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE INDEX ix_ar_due ON fin.ar_invoice (partner_id, status, due_date);
CREATE TABLE fin.ar_invoice_line (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          BIGINT        NOT NULL REFERENCES fin.ar_invoice(id) ON DELETE CASCADE,
    line_no             SMALLINT      NOT NULL,
    item_id             BIGINT REFERENCES sys.item(id),
    description         VARCHAR(255),
    qty                 NUMERIC(19,4) NOT NULL DEFAULT 1,
    unit_price          NUMERIC(19,4) NOT NULL DEFAULT 0,
    discount_pct        NUMERIC(7,4)  NOT NULL DEFAULT 0,
    amount              NUMERIC(19,2) NOT NULL DEFAULT 0,
    revenue_account_id  BIGINT        NOT NULL REFERENCES fin.account(id)
);

-- ---------------------------------------------------------------- FIN-21 Penerimaan pembayaran
CREATE TABLE fin.receipt (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no           VARCHAR(40)   NOT NULL UNIQUE,
    plant_id         BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date         DATE          NOT NULL,
    status           VARCHAR(12)   NOT NULL,
    partner_id       BIGINT        NOT NULL REFERENCES sys.partner(id),
    bank_account_id  BIGINT        NOT NULL REFERENCES fin.bank_account(id),
    reference        VARCHAR(64),
    description      VARCHAR(255),
    amount           NUMERIC(19,2) NOT NULL DEFAULT 0,
    reconciled       BOOLEAN       NOT NULL DEFAULT FALSE,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE TABLE fin.receipt_allocation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id  BIGINT        NOT NULL REFERENCES fin.receipt(id) ON DELETE CASCADE,
    line_no     SMALLINT      NOT NULL,
    invoice_id  BIGINT        NOT NULL REFERENCES fin.ar_invoice(id),
    amount      NUMERIC(19,2) NOT NULL CHECK (amount > 0)
);

-- ---------------------------------------------------------------- FIN-30 Kas kecil & uang muka kerja
CREATE TABLE fin.cash_voucher (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no           VARCHAR(40)   NOT NULL UNIQUE,
    plant_id         BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date         DATE          NOT NULL,
    status           VARCHAR(12)   NOT NULL,
    kind             VARCHAR(10)   NOT NULL,      -- EXPENSE / ADVANCE / SETTLEMENT
    cash_account_id  BIGINT        NOT NULL REFERENCES fin.bank_account(id),
    employee_id      BIGINT REFERENCES hc.employee(id),
    advance_id       BIGINT REFERENCES fin.cash_voucher(id),
    source_doc_no    VARCHAR(40),
    description      VARCHAR(255)  NOT NULL,
    amount           NUMERIC(19,2) NOT NULL DEFAULT 0,
    settled_amount   NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE TABLE fin.cash_voucher_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id      BIGINT        NOT NULL REFERENCES fin.cash_voucher(id) ON DELETE CASCADE,
    line_no         SMALLINT      NOT NULL,
    account_id      BIGINT        NOT NULL REFERENCES fin.account(id),
    cost_center_id  BIGINT REFERENCES sys.cost_center(id),
    description     VARCHAR(255),
    amount          NUMERIC(19,2) NOT NULL CHECK (amount > 0)
);

-- ---------------------------------------------------------------- FIN-31 Mutasi & rekonsiliasi bank
CREATE TABLE fin.bank_statement_line (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_account_id   BIGINT        NOT NULL REFERENCES fin.bank_account(id),
    txn_date          DATE          NOT NULL,
    description       VARCHAR(255),
    reference         VARCHAR(64),
    money_in          NUMERIC(19,2) NOT NULL DEFAULT 0,
    money_out         NUMERIC(19,2) NOT NULL DEFAULT 0,
    import_batch      VARCHAR(40)   NOT NULL,
    matched_doc_type  VARCHAR(16),
    matched_doc_id    BIGINT,
    matched_doc_no    VARCHAR(40),
    matched_by        BIGINT,
    matched_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CHECK (money_in >= 0 AND money_out >= 0)
);
CREATE INDEX ix_bsl_account ON fin.bank_statement_line (bank_account_id, txn_date);

-- ---------------------------------------------------------------- FIN-40 Aset tetap & penyusutan
CREATE TABLE fin.asset_category (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(16)  NOT NULL UNIQUE,
    name               VARCHAR(128) NOT NULL,
    asset_account_id   BIGINT       NOT NULL REFERENCES fin.account(id),
    accum_account_id   BIGINT       NOT NULL REFERENCES fin.account(id),
    expense_account_id BIGINT       NOT NULL REFERENCES fin.account(id),
    useful_life_months INTEGER      NOT NULL CHECK (useful_life_months > 0),
    method             VARCHAR(4)   NOT NULL DEFAULT 'SL',   -- SL / DDB
    fiscal_group       VARCHAR(16)  NOT NULL,                -- KEL1..KEL4 / BANGUNAN_P / BANGUNAN_NP
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    version            INTEGER      NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by         BIGINT,
    updated_at         TIMESTAMPTZ,
    updated_by         BIGINT
);
CREATE TABLE fin.fixed_asset (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no              VARCHAR(40)   NOT NULL UNIQUE,
    plant_id            BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date            DATE          NOT NULL,
    status              VARCHAR(12)   NOT NULL,
    name                VARCHAR(160)  NOT NULL,
    category_id         BIGINT        NOT NULL REFERENCES fin.asset_category(id),
    acquisition_cost    NUMERIC(19,2) NOT NULL CHECK (acquisition_cost > 0),
    residual_value      NUMERIC(19,2) NOT NULL DEFAULT 0,
    useful_life_months  INTEGER       NOT NULL,
    method              VARCHAR(4)    NOT NULL DEFAULT 'SL',
    depreciation_start  DATE          NOT NULL,
    cost_center_id      BIGINT REFERENCES sys.cost_center(id),
    location            VARCHAR(128),
    serial_no           VARCHAR(64),
    source_ref          VARCHAR(64),
    credit_account_id   BIGINT        NOT NULL REFERENCES fin.account(id),
    accumulated         NUMERIC(19,2) NOT NULL DEFAULT 0,
    fiscal_accumulated  NUMERIC(19,2) NOT NULL DEFAULT 0,
    asset_state         VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE / FULLY_DEP / DISPOSED
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE TABLE fin.depreciation_run (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no        VARCHAR(40)   NOT NULL UNIQUE,
    plant_id      BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date      DATE          NOT NULL,
    status        VARCHAR(12)   NOT NULL,
    period        VARCHAR(6)    NOT NULL,
    total_amount  NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_fiscal  NUMERIC(19,2) NOT NULL DEFAULT 0,
    asset_count   INTEGER       NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE UNIQUE INDEX ux_dep_period ON fin.depreciation_run (plant_id, period) WHERE status NOT IN ('CANCELLED');
CREATE TABLE fin.depreciation_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT        NOT NULL REFERENCES fin.depreciation_run(id) ON DELETE CASCADE,
    line_no         SMALLINT      NOT NULL,
    asset_id        BIGINT        NOT NULL REFERENCES fin.fixed_asset(id),
    amount          NUMERIC(19,2) NOT NULL,
    fiscal_amount   NUMERIC(19,2) NOT NULL,
    book_value_after NUMERIC(19,2) NOT NULL
);

-- ---------------------------------------------------------------- FIN-50/51 Anggaran & kontrol
CREATE TABLE fin.budget (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no       VARCHAR(40)   NOT NULL UNIQUE,
    plant_id     BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date     DATE          NOT NULL,
    status       VARCHAR(12)   NOT NULL,
    year         SMALLINT      NOT NULL,
    revision     SMALLINT      NOT NULL DEFAULT 0,
    kind         VARCHAR(6)    NOT NULL DEFAULT 'OPEX',  -- OPEX / CAPEX
    description  VARCHAR(255)  NOT NULL,
    total        NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE TABLE fin.budget_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id       BIGINT        NOT NULL REFERENCES fin.budget(id) ON DELETE CASCADE,
    line_no         SMALLINT      NOT NULL,
    cost_center_id  BIGINT        NOT NULL REFERENCES sys.cost_center(id),
    account_id      BIGINT        NOT NULL REFERENCES fin.account(id),
    m01 NUMERIC(19,2) NOT NULL DEFAULT 0, m02 NUMERIC(19,2) NOT NULL DEFAULT 0, m03 NUMERIC(19,2) NOT NULL DEFAULT 0,
    m04 NUMERIC(19,2) NOT NULL DEFAULT 0, m05 NUMERIC(19,2) NOT NULL DEFAULT 0, m06 NUMERIC(19,2) NOT NULL DEFAULT 0,
    m07 NUMERIC(19,2) NOT NULL DEFAULT 0, m08 NUMERIC(19,2) NOT NULL DEFAULT 0, m09 NUMERIC(19,2) NOT NULL DEFAULT 0,
    m10 NUMERIC(19,2) NOT NULL DEFAULT 0, m11 NUMERIC(19,2) NOT NULL DEFAULT 0, m12 NUMERIC(19,2) NOT NULL DEFAULT 0,
    total           NUMERIC(19,2) NOT NULL DEFAULT 0
);
CREATE INDEX ix_budget_line ON fin.budget_line (cost_center_id, account_id);

-- Komitmen anggaran dari PR/PO (dipakai mulai M2) dan dokumen biaya lain.
CREATE TABLE fin.budget_commitment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id         BIGINT        NOT NULL REFERENCES sys.plant(id),
    source_doc_type  VARCHAR(16)   NOT NULL,
    source_doc_id    BIGINT        NOT NULL,
    source_doc_no    VARCHAR(40)   NOT NULL,
    cost_center_id   BIGINT        NOT NULL REFERENCES sys.cost_center(id),
    account_id       BIGINT        NOT NULL REFERENCES fin.account(id),
    period           VARCHAR(6)    NOT NULL,
    amount           NUMERIC(19,2) NOT NULL,
    state            VARCHAR(10)   NOT NULL DEFAULT 'OPEN',   -- OPEN / CONSUMED / RELEASED
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_commit ON fin.budget_commitment (cost_center_id, account_id, period) WHERE state = 'OPEN';
