CREATE SCHEMA IF NOT EXISTS pre;

-- =====================================================================
-- M1 · Produksi (PRE): lini & parameter produk (PRE-99), Work Order (PRE-02),
-- hasil produksi & serah terima ke karantina (PRE-08), jam kerja lini (PRE-12).
-- =====================================================================

CREATE TABLE pre.line (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(16)  NOT NULL UNIQUE,
    name               VARCHAR(128) NOT NULL,
    plant_id           BIGINT       NOT NULL REFERENCES sys.plant(id),
    cost_center_id     BIGINT REFERENCES sys.cost_center(id),
    process_code       VARCHAR(24)  NOT NULL,    -- proses utama lini, dasar cek kualifikasi operator
    capacity_per_shift NUMERIC(19,4),
    capacity_uom       VARCHAR(12),
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    version            INTEGER      NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by         BIGINT,
    updated_at         TIMESTAMPTZ,
    updated_by         BIGINT
);

-- Parameter produksi per produk: awalan nomor batch, ukuran batch standar, yield minimum (PRE aturan 5).
CREATE TABLE pre.product_param (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id          BIGINT        NOT NULL UNIQUE REFERENCES sys.item(id),
    batch_prefix     VARCHAR(8)    NOT NULL,
    std_batch_size   NUMERIC(19,4) NOT NULL,
    min_yield_pct    NUMERIC(5,2)  NOT NULL DEFAULT 95,
    default_line_id  BIGINT REFERENCES pre.line(id),
    active           BOOLEAN       NOT NULL DEFAULT TRUE,
    version          INTEGER       NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT
);

CREATE TABLE pre.reject_reason (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(16)  NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    category    VARCHAR(16)  NOT NULL DEFAULT 'PROSES',   -- BAHAN / MESIN / PROSES / MANUSIA
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    version     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT
);

CREATE TABLE pre.work_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    product_item_id BIGINT        NOT NULL REFERENCES sys.item(id),
    batch_no        VARCHAR(40),
    qty_plan        NUMERIC(19,4) NOT NULL CHECK (qty_plan > 0),
    line_id         BIGINT        NOT NULL REFERENCES pre.line(id),
    shift_id        BIGINT REFERENCES sys.shift(id),
    planned_start   DATE          NOT NULL,
    planned_end     DATE          NOT NULL,
    mfg_date        DATE,
    exp_date        DATE,
    started_at      TIMESTAMPTZ,
    finished_at     TIMESTAMPTZ,
    qty_good        NUMERIC(19,4) NOT NULL DEFAULT 0,
    qty_reject      NUMERIC(19,4) NOT NULL DEFAULT 0,
    yield_pct       NUMERIC(7,2),
    source          VARCHAR(8)    NOT NULL DEFAULT 'MANUAL',   -- MANUAL / PPIC (SCM-07, M2)
    notes           TEXT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT,
    CHECK (planned_end >= planned_start)
);
CREATE UNIQUE INDEX ux_wo_batch ON pre.work_order (batch_no) WHERE batch_no IS NOT NULL;
CREATE TABLE pre.wo_operator (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_id         BIGINT       NOT NULL REFERENCES pre.work_order(id) ON DELETE CASCADE,
    line_no       SMALLINT     NOT NULL,
    employee_id   BIGINT       NOT NULL REFERENCES hc.employee(id),
    role          VARCHAR(10)  NOT NULL DEFAULT 'OPERATOR',   -- OPERATOR / CHECKER / LEADER
    process_code  VARCHAR(24)  NOT NULL
);

CREATE TABLE pre.production_output (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no             VARCHAR(40)   NOT NULL UNIQUE,
    plant_id           BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date           DATE          NOT NULL,
    status             VARCHAR(12)   NOT NULL,
    wo_id              BIGINT        NOT NULL REFERENCES pre.work_order(id),
    qty_good           NUMERIC(19,4) NOT NULL CHECK (qty_good >= 0),
    qty_reject         NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK (qty_reject >= 0),
    reject_reason_id   BIGINT REFERENCES pre.reject_reason(id),
    yield_pct          NUMERIC(7,2),
    yield_explanation  TEXT,
    to_location_id     BIGINT        NOT NULL REFERENCES sys.location(id),
    lot_id             BIGINT REFERENCES scm.lot(id),
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

-- PRE-12 Jam kerja lini per WO (dasar biaya tenaga kerja batch di FIN-53).
CREATE TABLE pre.labor_entry (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_id        BIGINT       NOT NULL REFERENCES pre.work_order(id),
    employee_id  BIGINT       NOT NULL REFERENCES hc.employee(id),
    work_date    DATE         NOT NULL,
    hours        NUMERIC(5,2) NOT NULL CHECK (hours > 0 AND hours <= 16),
    activity     VARCHAR(128),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    version      INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ,
    updated_by   BIGINT
);
CREATE INDEX ix_labor_emp ON pre.labor_entry (employee_id, work_date);
