-- =====================================================================
-- M2 (PRD Fase 2): Procurement (PRC), Supply Chain (SCM: PPIC, Warehouse, Inventory Control),
-- PRE permintaan & retur bahan, FIN costing per batch & pajak.
-- Alur ujung-ke-ujung: Procure to Pay dan Order to Cash.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS prc;

-- ---------------------------------------------------------------- PRC-03 Supplier, PRC-04 ASL, PRC-08 Daftar harga

CREATE TABLE prc.supplier_profile (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id           BIGINT       NOT NULL UNIQUE REFERENCES sys.partner(id),
    legal_name           VARCHAR(160),
    nib                  VARCHAR(32),
    bank_name            VARCHAR(64),
    bank_account_no      VARCHAR(40),
    bank_account_name    VARCHAR(128),
    contact_person       VARCHAR(128),
    halal_cert_no        VARCHAR(64),
    halal_cert_expiry    DATE,
    other_certs          VARCHAR(255),
    qualification_status VARCHAR(16)  NOT NULL DEFAULT 'PENDING',   -- PENDING / QUALIFIED / CONDITIONAL / DISQUALIFIED
    qualified_at         DATE,
    notes                TEXT,
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE prc.asl (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id       BIGINT       NOT NULL REFERENCES sys.item(id),
    partner_id    BIGINT       NOT NULL REFERENCES sys.partner(id),
    manufacturer  VARCHAR(160) NOT NULL DEFAULT '-',
    status        VARCHAR(12)  NOT NULL DEFAULT 'APPROVED',   -- APPROVED / CONDITIONAL / BLOCKED
    valid_until   DATE,
    notes         TEXT,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT,
    UNIQUE (item_id, partner_id, manufacturer)
);

CREATE TABLE prc.price_list (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id      BIGINT        NOT NULL REFERENCES sys.partner(id),
    item_id         BIGINT        NOT NULL REFERENCES sys.item(id),
    contract_no     VARCHAR(64),
    price           NUMERIC(19,4) NOT NULL CHECK (price >= 0),
    currency_code   VARCHAR(3)    NOT NULL DEFAULT 'IDR' REFERENCES sys.currency(code),
    min_qty         NUMERIC(19,4) NOT NULL DEFAULT 0,
    lead_time_days  INTEGER       NOT NULL DEFAULT 14,
    valid_from      DATE          NOT NULL,
    valid_until     DATE,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE INDEX ix_price_item ON prc.price_list (item_id, partner_id, valid_from);

-- ---------------------------------------------------------------- PRC-02 Purchase Requisition

CREATE TABLE prc.pr (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    source          VARCHAR(8)    NOT NULL DEFAULT 'MANUAL',   -- MANUAL / MRP / ESS / PRE / GA
    cost_center_id  BIGINT REFERENCES sys.cost_center(id),
    need_date       DATE,
    purpose         TEXT,
    total_est       NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE prc.pr_line (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_id                 BIGINT        NOT NULL REFERENCES prc.pr(id) ON DELETE CASCADE,
    line_no               SMALLINT      NOT NULL,
    item_id               BIGINT        NOT NULL REFERENCES sys.item(id),
    description           VARCHAR(255),
    qty                   NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    need_date             DATE,
    est_price             NUMERIC(19,4) NOT NULL DEFAULT 0,
    amount                NUMERIC(19,2) NOT NULL DEFAULT 0,
    cost_center_id        BIGINT REFERENCES sys.cost_center(id),
    account_id            BIGINT REFERENCES fin.account(id),
    suggested_partner_id  BIGINT REFERENCES sys.partner(id),
    qty_ordered           NUMERIC(19,4) NOT NULL DEFAULT 0,
    closed                BOOLEAN       NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_pr_line_open ON prc.pr_line (item_id) WHERE NOT closed;

-- ---------------------------------------------------------------- PRC-05/06 RFQ & perbandingan penawaran

CREATE TABLE prc.rfq (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no              VARCHAR(40)   NOT NULL UNIQUE,
    plant_id            BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date            DATE          NOT NULL,
    status              VARCHAR(12)   NOT NULL,
    pr_id               BIGINT REFERENCES prc.pr(id),
    due_date            DATE,
    notes               TEXT,
    awarded_partner_id  BIGINT REFERENCES sys.partner(id),
    award_reason        TEXT,
    po_id               BIGINT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE prc.rfq_line (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfq_id       BIGINT        NOT NULL REFERENCES prc.rfq(id) ON DELETE CASCADE,
    line_no      SMALLINT      NOT NULL,
    pr_line_id   BIGINT REFERENCES prc.pr_line(id),
    item_id      BIGINT        NOT NULL REFERENCES sys.item(id),
    description  VARCHAR(255),
    qty          NUMERIC(19,4) NOT NULL CHECK (qty > 0)
);

CREATE TABLE prc.rfq_supplier (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfq_id      BIGINT       NOT NULL REFERENCES prc.rfq(id) ON DELETE CASCADE,
    line_no     SMALLINT     NOT NULL,
    partner_id  BIGINT       NOT NULL REFERENCES sys.partner(id),
    UNIQUE (rfq_id, partner_id)
);

-- Penawaran diisi setelah RFQ dikirim (tidak ikut siklus draft).
CREATE TABLE prc.rfq_quote (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfq_id             BIGINT        NOT NULL REFERENCES prc.rfq(id) ON DELETE CASCADE,
    rfq_line_id        BIGINT        NOT NULL REFERENCES prc.rfq_line(id) ON DELETE CASCADE,
    partner_id         BIGINT        NOT NULL REFERENCES sys.partner(id),
    price              NUMERIC(19,4) NOT NULL CHECK (price >= 0),
    lead_time_days     INTEGER,
    payment_term_days  INTEGER,
    valid_until        DATE,
    notes              VARCHAR(255),
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by         BIGINT,
    UNIQUE (rfq_line_id, partner_id)
);

-- ---------------------------------------------------------------- PRC-07 Purchase Order

CREATE TABLE prc.po (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no                VARCHAR(40)   NOT NULL UNIQUE,
    plant_id              BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date              DATE          NOT NULL,
    status                VARCHAR(12)   NOT NULL,
    partner_id            BIGINT        NOT NULL REFERENCES sys.partner(id),
    kind                  VARCHAR(8)    NOT NULL DEFAULT 'GOODS',   -- GOODS / SERVICE
    currency_code         VARCHAR(3)    NOT NULL DEFAULT 'IDR' REFERENCES sys.currency(code),
    exchange_rate         NUMERIC(19,6) NOT NULL DEFAULT 1,
    payment_term_days     INTEGER       NOT NULL DEFAULT 30,
    delivery_date         DATE,
    warehouse_id          BIGINT REFERENCES sys.warehouse(id),
    with_ppn              BOOLEAN       NOT NULL DEFAULT TRUE,
    import_po             BOOLEAN       NOT NULL DEFAULT FALSE,
    rfq_id                BIGINT REFERENCES prc.rfq(id),
    single_source_reason  TEXT,
    subtotal              NUMERIC(19,2) NOT NULL DEFAULT 0,
    ppn_amount            NUMERIC(19,2) NOT NULL DEFAULT 0,
    total                 NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_idr             NUMERIC(19,2) NOT NULL DEFAULT 0,
    notes                 TEXT,
    closed_reason         TEXT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE INDEX ix_po_partner ON prc.po (partner_id, status);
ALTER TABLE prc.rfq ADD CONSTRAINT fk_rfq_po FOREIGN KEY (po_id) REFERENCES prc.po(id);

CREATE TABLE prc.po_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id           BIGINT        NOT NULL REFERENCES prc.po(id) ON DELETE CASCADE,
    line_no         SMALLINT      NOT NULL,
    pr_line_id      BIGINT REFERENCES prc.pr_line(id),
    item_id         BIGINT        NOT NULL REFERENCES sys.item(id),
    description     VARCHAR(255),
    qty             NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    unit_price      NUMERIC(19,4) NOT NULL DEFAULT 0,
    discount_pct    NUMERIC(7,4)  NOT NULL DEFAULT 0,
    amount          NUMERIC(19,2) NOT NULL DEFAULT 0,
    need_date       DATE,
    eta             DATE,
    followup_note   VARCHAR(255),
    cost_center_id  BIGINT REFERENCES sys.cost_center(id),
    account_id      BIGINT REFERENCES fin.account(id),
    received_qty    NUMERIC(19,4) NOT NULL DEFAULT 0,
    first_receipt   DATE,
    last_receipt    DATE,
    closed          BOOLEAN       NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_po_line_item ON prc.po_line (item_id) WHERE NOT closed;

-- ---------------------------------------------------------------- PRC-12 Jasa & BAST

CREATE TABLE prc.bast (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    po_id           BIGINT        NOT NULL REFERENCES prc.po(id),
    service_from    DATE,
    service_to      DATE,
    notes           TEXT,
    total           NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE prc.bast_line (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bast_id          BIGINT        NOT NULL REFERENCES prc.bast(id) ON DELETE CASCADE,
    line_no          SMALLINT      NOT NULL,
    po_line_id       BIGINT        NOT NULL REFERENCES prc.po_line(id),
    qty              NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    amount           NUMERIC(19,2) NOT NULL DEFAULT 0,
    acceptance_note  VARCHAR(255)
);

-- ---------------------------------------------------------------- PRC-10 Impor & landed cost

CREATE TABLE prc.landed_cost (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    po_id           BIGINT        NOT NULL REFERENCES prc.po(id),
    shipment_no     VARCHAR(64),
    bl_no           VARCHAR(64),
    pib_no          VARCHAR(64),
    pib_date        DATE,
    arrival_date    DATE,
    alloc_basis     VARCHAR(8)    NOT NULL DEFAULT 'VALUE',   -- VALUE / QTY
    notes           TEXT,
    capitalized     NUMERIC(19,2) NOT NULL DEFAULT 0,
    tax_credit      NUMERIC(19,2) NOT NULL DEFAULT 0,
    total           NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE prc.lc_charge (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lc_id        BIGINT        NOT NULL REFERENCES prc.landed_cost(id) ON DELETE CASCADE,
    line_no      SMALLINT      NOT NULL,
    kind         VARCHAR(12)   NOT NULL,   -- FREIGHT / INSURANCE / DUTY / HANDLING / OTHER / PPN_IMPORT / PPH22_IMPORT
    partner_id   BIGINT REFERENCES sys.partner(id),
    reference    VARCHAR(64),
    amount       NUMERIC(19,2) NOT NULL CHECK (amount >= 0)
);

-- Hasil alokasi biaya ke baris GR (diisi sistem saat simpan).
CREATE TABLE prc.lc_alloc (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lc_id        BIGINT        NOT NULL REFERENCES prc.landed_cost(id) ON DELETE CASCADE,
    line_no      SMALLINT      NOT NULL,
    gr_line_id   BIGINT        NOT NULL,
    item_id      BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id       BIGINT,
    qty          NUMERIC(19,4) NOT NULL,
    base_value   NUMERIC(19,2) NOT NULL,
    allocated    NUMERIC(19,2) NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------- PRC-11 / SCM-28 Retur ke supplier

CREATE TABLE prc.supplier_return (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    partner_id      BIGINT        NOT NULL REFERENCES sys.partner(id),
    po_id           BIGINT REFERENCES prc.po(id),
    reason          TEXT,
    claim_type      VARCHAR(12)   NOT NULL DEFAULT 'REPLACE',   -- REPLACE / DEBIT_NOTE
    debit_note_no   VARCHAR(64),
    total           NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE prc.supplier_return_line (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id     BIGINT        NOT NULL REFERENCES prc.supplier_return(id) ON DELETE CASCADE,
    line_no       SMALLINT      NOT NULL,
    po_line_id    BIGINT REFERENCES prc.po_line(id),
    item_id       BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id        BIGINT REFERENCES scm.lot(id),
    location_id   BIGINT        NOT NULL REFERENCES sys.location(id),
    qty           NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    unit_cost     NUMERIC(19,6) NOT NULL DEFAULT 0,
    amount        NUMERIC(19,2) NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------- SCM-05 BOM (dikelola RnD di M3: RND-04)

CREATE TABLE scm.bom (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    item_id         BIGINT        NOT NULL REFERENCES sys.item(id),
    revision        INTEGER       NOT NULL DEFAULT 1,
    base_qty        NUMERIC(19,4) NOT NULL CHECK (base_qty > 0),
    std_hours       NUMERIC(9,2)  NOT NULL DEFAULT 0,
    effective_from  DATE,
    notes           TEXT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);
CREATE INDEX ix_bom_item ON scm.bom (item_id, status);

CREATE TABLE scm.bom_line (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id             BIGINT        NOT NULL REFERENCES scm.bom(id) ON DELETE CASCADE,
    line_no            SMALLINT      NOT NULL,
    component_item_id  BIGINT        NOT NULL REFERENCES sys.item(id),
    qty                NUMERIC(19,6) NOT NULL CHECK (qty > 0),
    scrap_pct          NUMERIC(7,4)  NOT NULL DEFAULT 0,
    notes              VARCHAR(255)
);

-- ---------------------------------------------------------------- SCM-02 Pesanan pelanggan

CREATE TABLE scm.so (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    partner_id      BIGINT        NOT NULL REFERENCES sys.partner(id),
    customer_po     VARCHAR(64),
    delivery_date   DATE,
    ship_to         TEXT,
    with_ppn        BOOLEAN       NOT NULL DEFAULT TRUE,
    subtotal        NUMERIC(19,2) NOT NULL DEFAULT 0,
    ppn_amount      NUMERIC(19,2) NOT NULL DEFAULT 0,
    total           NUMERIC(19,2) NOT NULL DEFAULT 0,
    credit_hold     BOOLEAN       NOT NULL DEFAULT FALSE,
    hold_reason     TEXT,
    notes           TEXT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE scm.so_line (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_id          BIGINT        NOT NULL REFERENCES scm.so(id) ON DELETE CASCADE,
    line_no        SMALLINT      NOT NULL,
    item_id        BIGINT        NOT NULL REFERENCES sys.item(id),
    qty            NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    unit_price     NUMERIC(19,4) NOT NULL DEFAULT 0,
    discount_pct   NUMERIC(7,4)  NOT NULL DEFAULT 0,
    amount         NUMERIC(19,2) NOT NULL DEFAULT 0,
    delivery_date  DATE,
    qty_shipped    NUMERIC(19,4) NOT NULL DEFAULT 0,
    closed         BOOLEAN       NOT NULL DEFAULT FALSE
);

-- ---------------------------------------------------------------- SCM-03 Forecast & S&OP, SCM-04 MPS, SCM-43 Parameter stok

CREATE TABLE scm.forecast (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id   BIGINT        NOT NULL REFERENCES sys.plant(id),
    item_id    BIGINT        NOT NULL REFERENCES sys.item(id),
    period     VARCHAR(6)    NOT NULL,   -- yyyyMM
    qty        NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK (qty >= 0),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by BIGINT,
    UNIQUE (plant_id, item_id, period)
);

CREATE TABLE scm.sop_note (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id    BIGINT       NOT NULL REFERENCES sys.plant(id),
    period      VARCHAR(6)   NOT NULL,
    meeting_on  DATE,
    decisions   TEXT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    UNIQUE (plant_id, period)
);

CREATE TABLE scm.mps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id    BIGINT        NOT NULL REFERENCES sys.plant(id),
    item_id     BIGINT        NOT NULL REFERENCES sys.item(id),
    week_start  DATE          NOT NULL,
    qty         NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK (qty >= 0),
    firm        BOOLEAN       NOT NULL DEFAULT FALSE,
    line_id     BIGINT,
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    UNIQUE (plant_id, item_id, week_start)
);

CREATE TABLE scm.stock_param (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    item_id         BIGINT        NOT NULL REFERENCES sys.item(id),
    min_qty         NUMERIC(19,4) NOT NULL DEFAULT 0,
    max_qty         NUMERIC(19,4),
    reorder_point   NUMERIC(19,4) NOT NULL DEFAULT 0,
    safety_stock    NUMERIC(19,4) NOT NULL DEFAULT 0,
    lead_time_days  INTEGER       NOT NULL DEFAULT 14,
    moq             NUMERIC(19,4) NOT NULL DEFAULT 0,
    lot_size        NUMERIC(19,4) NOT NULL DEFAULT 0,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT,
    UNIQUE (plant_id, item_id)
);

-- ---------------------------------------------------------------- SCM-05 MRP

CREATE TABLE scm.mrp_run (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id       BIGINT       NOT NULL REFERENCES sys.plant(id),
    run_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    horizon_weeks  INTEGER      NOT NULL,
    duration_ms    BIGINT,
    lines          INTEGER      NOT NULL DEFAULT 0,
    trigger        VARCHAR(8)   NOT NULL DEFAULT 'MANUAL',   -- MANUAL / NIGHTLY
    triggered_by   BIGINT,
    notes          TEXT
);

CREATE TABLE scm.mrp_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT        NOT NULL REFERENCES scm.mrp_run(id) ON DELETE CASCADE,
    item_id         BIGINT        NOT NULL REFERENCES sys.item(id),
    level           SMALLINT      NOT NULL,
    action          VARCHAR(6)    NOT NULL,   -- BUY / MAKE
    gross_req       NUMERIC(19,4) NOT NULL,
    on_hand         NUMERIC(19,4) NOT NULL,
    quarantine      NUMERIC(19,4) NOT NULL DEFAULT 0,
    on_order        NUMERIC(19,4) NOT NULL,
    safety_stock    NUMERIC(19,4) NOT NULL,
    net_req         NUMERIC(19,4) NOT NULL,
    planned_qty     NUMERIC(19,4) NOT NULL,
    need_date       DATE          NOT NULL,
    order_date      DATE          NOT NULL,
    partner_id      BIGINT REFERENCES sys.partner(id),
    est_price       NUMERIC(19,4),
    pr_line_id      BIGINT REFERENCES prc.pr_line(id),
    pegging         TEXT
);
CREATE INDEX ix_mrp_line_run ON scm.mrp_line (run_id);

-- ---------------------------------------------------------------- SCM-20 Penerimaan barang (GR)

CREATE TABLE scm.gr (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no            VARCHAR(40)   NOT NULL UNIQUE,
    plant_id          BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date          DATE          NOT NULL,
    status            VARCHAR(12)   NOT NULL,
    partner_id        BIGINT        NOT NULL REFERENCES sys.partner(id),
    po_id             BIGINT        NOT NULL REFERENCES prc.po(id),
    delivery_note_no  VARCHAR(64),
    vehicle_no        VARCHAR(32),
    notes             TEXT,
    total             NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE scm.gr_line (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gr_id          BIGINT        NOT NULL REFERENCES scm.gr(id) ON DELETE CASCADE,
    line_no        SMALLINT      NOT NULL,
    po_line_id     BIGINT        NOT NULL REFERENCES prc.po_line(id),
    item_id        BIGINT        NOT NULL REFERENCES sys.item(id),
    qty            NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    supplier_lot   VARCHAR(64),
    manufacturer   VARCHAR(160),
    mfg_date       DATE,
    exp_date       DATE,
    location_id    BIGINT REFERENCES sys.location(id),
    lot_id         BIGINT REFERENCES scm.lot(id),
    unit_cost      NUMERIC(19,6) NOT NULL DEFAULT 0,
    amount         NUMERIC(19,2) NOT NULL DEFAULT 0
);
CREATE INDEX ix_gr_line_po ON scm.gr_line (po_line_id);
ALTER TABLE prc.lc_alloc ADD CONSTRAINT fk_lc_gr_line FOREIGN KEY (gr_line_id) REFERENCES scm.gr_line(id);

-- ---------------------------------------------------------------- SCM-25 Transfer, SCM-29 Pengeluaran non-produksi

CREATE TABLE scm.transfer (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no            VARCHAR(40)   NOT NULL UNIQUE,
    plant_id          BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date          DATE          NOT NULL,
    status            VARCHAR(12)   NOT NULL,
    notes             TEXT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE scm.transfer_line (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id       BIGINT        NOT NULL REFERENCES scm.transfer(id) ON DELETE CASCADE,
    line_no           SMALLINT      NOT NULL,
    item_id           BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id            BIGINT REFERENCES scm.lot(id),
    from_location_id  BIGINT        NOT NULL REFERENCES sys.location(id),
    to_location_id    BIGINT        NOT NULL REFERENCES sys.location(id),
    qty               NUMERIC(19,4) NOT NULL CHECK (qty > 0)
);

CREATE TABLE scm.goods_issue (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no           VARCHAR(40)   NOT NULL UNIQUE,
    plant_id         BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date         DATE          NOT NULL,
    status           VARCHAR(12)   NOT NULL,
    cost_center_id   BIGINT        NOT NULL REFERENCES sys.cost_center(id),
    purpose          TEXT,
    total            NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE scm.goods_issue_line (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id      BIGINT        NOT NULL REFERENCES scm.goods_issue(id) ON DELETE CASCADE,
    line_no       SMALLINT      NOT NULL,
    item_id       BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id        BIGINT REFERENCES scm.lot(id),
    location_id   BIGINT        NOT NULL REFERENCES sys.location(id),
    qty           NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    account_id    BIGINT REFERENCES fin.account(id),
    unit_cost     NUMERIC(19,6) NOT NULL DEFAULT 0,
    amount        NUMERIC(19,2) NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------- SCM-26 Surat jalan, SCM-27 Retur pelanggan

CREATE TABLE scm.delivery (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no                 VARCHAR(40)   NOT NULL UNIQUE,
    plant_id               BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date               DATE          NOT NULL,
    status                 VARCHAR(12)   NOT NULL,
    partner_id             BIGINT        NOT NULL REFERENCES sys.partner(id),
    so_id                  BIGINT        NOT NULL REFERENCES scm.so(id),
    expedition_partner_id  BIGINT REFERENCES sys.partner(id),
    vehicle_no             VARCHAR(32),
    driver                 VARCHAR(64),
    ship_to                TEXT,
    notes                  TEXT,
    credit_hold            BOOLEAN       NOT NULL DEFAULT FALSE,
    hold_reason            TEXT,
    total_value            NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_cost             NUMERIC(19,2) NOT NULL DEFAULT 0,
    ar_invoice_id          BIGINT,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE scm.delivery_line (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id   BIGINT        NOT NULL REFERENCES scm.delivery(id) ON DELETE CASCADE,
    line_no       SMALLINT      NOT NULL,
    so_line_id    BIGINT        NOT NULL REFERENCES scm.so_line(id),
    item_id       BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id        BIGINT REFERENCES scm.lot(id),
    location_id   BIGINT REFERENCES sys.location(id),
    qty           NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    unit_price    NUMERIC(19,4) NOT NULL DEFAULT 0,
    unit_cost     NUMERIC(19,6) NOT NULL DEFAULT 0
);

CREATE TABLE scm.customer_return (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    partner_id      BIGINT        NOT NULL REFERENCES sys.partner(id),
    delivery_id     BIGINT        NOT NULL REFERENCES scm.delivery(id),
    reason          TEXT,
    with_ppn        BOOLEAN       NOT NULL DEFAULT TRUE,
    subtotal        NUMERIC(19,2) NOT NULL DEFAULT 0,
    ppn_amount      NUMERIC(19,2) NOT NULL DEFAULT 0,
    total           NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE scm.customer_return_line (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id          BIGINT        NOT NULL REFERENCES scm.customer_return(id) ON DELETE CASCADE,
    line_no            SMALLINT      NOT NULL,
    delivery_line_id   BIGINT        NOT NULL REFERENCES scm.delivery_line(id),
    item_id            BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id             BIGINT REFERENCES scm.lot(id),
    qty                NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    location_id        BIGINT REFERENCES sys.location(id),
    unit_price         NUMERIC(19,4) NOT NULL DEFAULT 0,
    unit_cost          NUMERIC(19,6) NOT NULL DEFAULT 0,
    amount             NUMERIC(19,2) NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------- SCM-41 Opname, SCM-42 Penyesuaian, SCM-46 Pemusnahan

CREATE TABLE scm.stock_count (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    warehouse_id    BIGINT        NOT NULL REFERENCES sys.warehouse(id),
    kind            VARCHAR(8)    NOT NULL DEFAULT 'CYCLE',   -- FULL / CYCLE
    notes           TEXT,
    lines_total     INTEGER       NOT NULL DEFAULT 0,
    lines_accurate  INTEGER       NOT NULL DEFAULT 0,
    diff_value      NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE scm.stock_count_line (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count_id      BIGINT        NOT NULL REFERENCES scm.stock_count(id) ON DELETE CASCADE,
    line_no       SMALLINT      NOT NULL,
    item_id       BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id        BIGINT REFERENCES scm.lot(id),
    location_id   BIGINT        NOT NULL REFERENCES sys.location(id),
    system_qty    NUMERIC(19,4) NOT NULL DEFAULT 0,
    counted_qty   NUMERIC(19,4),
    diff_qty      NUMERIC(19,4) NOT NULL DEFAULT 0,
    unit_cost     NUMERIC(19,6) NOT NULL DEFAULT 0,
    diff_value    NUMERIC(19,2) NOT NULL DEFAULT 0,
    note          VARCHAR(255)
);

CREATE TABLE scm.stock_adjustment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    reason          TEXT,
    count_id        BIGINT REFERENCES scm.stock_count(id),
    total_value     NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE scm.stock_adjustment_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_id   BIGINT        NOT NULL REFERENCES scm.stock_adjustment(id) ON DELETE CASCADE,
    line_no         SMALLINT      NOT NULL,
    item_id         BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id          BIGINT REFERENCES scm.lot(id),
    location_id     BIGINT        NOT NULL REFERENCES sys.location(id),
    qty_delta       NUMERIC(19,4) NOT NULL CHECK (qty_delta <> 0),
    unit_cost       NUMERIC(19,6) NOT NULL DEFAULT 0,
    amount          NUMERIC(19,2) NOT NULL DEFAULT 0,
    note            VARCHAR(255)
);

CREATE TABLE scm.scrap (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    reason          TEXT,
    method          VARCHAR(64),
    witnesses       VARCHAR(255),
    vendor_partner_id BIGINT REFERENCES sys.partner(id),
    total_value     NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE scm.scrap_line (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scrap_id      BIGINT        NOT NULL REFERENCES scm.scrap(id) ON DELETE CASCADE,
    line_no       SMALLINT      NOT NULL,
    item_id       BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id        BIGINT REFERENCES scm.lot(id),
    location_id   BIGINT        NOT NULL REFERENCES sys.location(id),
    qty           NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    unit_cost     NUMERIC(19,6) NOT NULL DEFAULT 0,
    amount        NUMERIC(19,2) NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------- PRE-04 Permintaan bahan, PRE-10 Retur sisa bahan

CREATE TABLE pre.material_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    wo_id           BIGINT        NOT NULL REFERENCES pre.work_order(id),
    needed_at       DATE,
    notes           TEXT,
    issued_at       TIMESTAMPTZ,
    issued_by       BIGINT,
    issued_value    NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE pre.material_request_line (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    BIGINT        NOT NULL REFERENCES pre.material_request(id) ON DELETE CASCADE,
    line_no       SMALLINT      NOT NULL,
    item_id       BIGINT        NOT NULL REFERENCES sys.item(id),
    qty_bom       NUMERIC(19,4) NOT NULL DEFAULT 0,
    qty           NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    qty_issued    NUMERIC(19,4) NOT NULL DEFAULT 0,
    note          VARCHAR(255)
);

CREATE TABLE pre.material_return (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    wo_id           BIGINT        NOT NULL REFERENCES pre.work_order(id),
    notes           TEXT,
    received_at     TIMESTAMPTZ,
    received_by     BIGINT,
    returned_value  NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE pre.material_return_line (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id      BIGINT        NOT NULL REFERENCES pre.material_return(id) ON DELETE CASCADE,
    line_no        SMALLINT      NOT NULL,
    item_id        BIGINT        NOT NULL REFERENCES sys.item(id),
    lot_id         BIGINT REFERENCES scm.lot(id),
    qty            NUMERIC(19,4) NOT NULL CHECK (qty > 0),
    location_id    BIGINT REFERENCES sys.location(id),
    unit_cost      NUMERIC(19,6) NOT NULL DEFAULT 0
);

ALTER TABLE pre.production_output
    ADD COLUMN received_qty  NUMERIC(19,4),
    ADD COLUMN received_by   BIGINT,
    ADD COLUMN received_at   TIMESTAMPTZ,
    ADD COLUMN receive_note  VARCHAR(255),
    ADD COLUMN unit_cost     NUMERIC(19,6) NOT NULL DEFAULT 0,
    ADD COLUMN total_cost    NUMERIC(19,2) NOT NULL DEFAULT 0;

-- ---------------------------------------------------------------- FIN-52..55 Costing

CREATE TABLE fin.std_cost (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id      BIGINT        NOT NULL REFERENCES sys.plant(id),
    item_id       BIGINT        NOT NULL REFERENCES sys.item(id),
    bom_id        BIGINT REFERENCES scm.bom(id),
    material      NUMERIC(19,6) NOT NULL DEFAULT 0,
    labor         NUMERIC(19,6) NOT NULL DEFAULT 0,
    overhead      NUMERIC(19,6) NOT NULL DEFAULT 0,
    total         NUMERIC(19,6) NOT NULL DEFAULT 0,
    calc_date     DATE          NOT NULL,
    current       BOOLEAN       NOT NULL DEFAULT TRUE,
    detail        TEXT,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by    BIGINT
);
CREATE UNIQUE INDEX ux_std_cost_current ON fin.std_cost (plant_id, item_id) WHERE current;

-- Tarif per jam tenaga kerja & overhead per cost center produksi.
CREATE TABLE fin.cost_rate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    cost_center_id  BIGINT        NOT NULL REFERENCES sys.cost_center(id),
    valid_from      DATE          NOT NULL,
    labor_rate      NUMERIC(19,2) NOT NULL DEFAULT 0,
    overhead_rate   NUMERIC(19,2) NOT NULL DEFAULT 0,
    source          VARCHAR(10)   NOT NULL DEFAULT 'MANUAL',   -- MANUAL / ALLOCATION
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE fin.batch_cost (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id          BIGINT        NOT NULL REFERENCES sys.plant(id),
    wo_id             BIGINT        NOT NULL UNIQUE REFERENCES pre.work_order(id),
    item_id           BIGINT        NOT NULL REFERENCES sys.item(id),
    batch_no          VARCHAR(40),
    qty_good          NUMERIC(19,4) NOT NULL DEFAULT 0,
    material          NUMERIC(19,2) NOT NULL DEFAULT 0,
    labor_hours       NUMERIC(19,2) NOT NULL DEFAULT 0,
    labor             NUMERIC(19,2) NOT NULL DEFAULT 0,
    overhead          NUMERIC(19,2) NOT NULL DEFAULT 0,
    total             NUMERIC(19,2) NOT NULL DEFAULT 0,
    unit_cost         NUMERIC(19,6) NOT NULL DEFAULT 0,
    std_unit_cost     NUMERIC(19,6) NOT NULL DEFAULT 0,
    fg_value          NUMERIC(19,2) NOT NULL DEFAULT 0,
    variance          NUMERIC(19,2) NOT NULL DEFAULT 0,
    closed_at         TIMESTAMPTZ,
    closed_by         BIGINT,
    journal_doc_no    VARCHAR(40)
);

CREATE TABLE fin.overhead_alloc (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no          VARCHAR(40)   NOT NULL UNIQUE,
    plant_id        BIGINT        NOT NULL REFERENCES sys.plant(id),
    doc_date        DATE          NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    period          VARCHAR(6)    NOT NULL,
    basis           VARCHAR(12)   NOT NULL DEFAULT 'LABOR_HOURS',   -- LABOR_HOURS / OUTPUT
    notes           TEXT,
    total           NUMERIC(19,2) NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ, approved_by BIGINT, approved_at TIMESTAMPTZ, posted_by BIGINT, posted_at TIMESTAMPTZ,
    cancelled_by BIGINT, cancelled_at TIMESTAMPTZ, cancel_reason TEXT,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

CREATE TABLE fin.overhead_alloc_line (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alloc_id          BIGINT        NOT NULL REFERENCES fin.overhead_alloc(id) ON DELETE CASCADE,
    line_no           SMALLINT      NOT NULL,
    source_cc_id      BIGINT        NOT NULL REFERENCES sys.cost_center(id),
    account_id        BIGINT        NOT NULL REFERENCES fin.account(id),
    target_cc_id      BIGINT        NOT NULL REFERENCES sys.cost_center(id),
    basis_qty         NUMERIC(19,4) NOT NULL DEFAULT 0,
    share_pct         NUMERIC(9,4)  NOT NULL DEFAULT 0,
    amount            NUMERIC(19,2) NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------- FIN-60..63 Pajak

CREATE TABLE fin.tax_period (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id       BIGINT        NOT NULL REFERENCES sys.plant(id),
    period         VARCHAR(6)    NOT NULL,
    tax_type       VARCHAR(8)    NOT NULL,   -- PPN / PPH21 / PPH23 / PPH4_2 / PPH22
    amount         NUMERIC(19,2) NOT NULL DEFAULT 0,
    billing_code   VARCHAR(32),
    ntpn           VARCHAR(32),
    paid_date      DATE,
    reported_date  DATE,
    bpe_no         VARCHAR(64),
    status         VARCHAR(10)   NOT NULL DEFAULT 'OPEN',   -- OPEN / PAID / REPORTED
    notes          TEXT,
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by     BIGINT,
    UNIQUE (plant_id, period, tax_type)
);

CREATE TABLE fin.withholding_slip (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id         BIGINT        NOT NULL REFERENCES sys.plant(id),
    tax_type         VARCHAR(8)    NOT NULL,
    period           VARCHAR(6)    NOT NULL,
    slip_no          VARCHAR(40)   NOT NULL UNIQUE,
    partner_id       BIGINT REFERENCES sys.partner(id),
    employee_id      BIGINT,
    npwp             VARCHAR(32),
    source_doc_type  VARCHAR(16)   NOT NULL,
    source_doc_id    BIGINT        NOT NULL,
    source_doc_no    VARCHAR(40)   NOT NULL,
    dpp              NUMERIC(19,2) NOT NULL,
    rate             NUMERIC(7,4)  NOT NULL,
    tax              NUMERIC(19,2) NOT NULL,
    issued_date      DATE          NOT NULL,
    status           VARCHAR(10)   NOT NULL DEFAULT 'ISSUED',   -- ISSUED / CANCELLED
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       BIGINT,
    UNIQUE (tax_type, source_doc_type, source_doc_id, employee_id)
);

CREATE TABLE fin.fiscal_correction (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id      BIGINT        REFERENCES sys.plant(id),
    year          SMALLINT      NOT NULL,
    description   VARCHAR(255)  NOT NULL,
    kind          VARCHAR(8)    NOT NULL,     -- POSITIVE / NEGATIVE
    category      VARCHAR(10)   NOT NULL DEFAULT 'TETAP',   -- TETAP / WAKTU
    account_id    BIGINT REFERENCES fin.account(id),
    amount        NUMERIC(19,2) NOT NULL DEFAULT 0,
    notes         TEXT,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ, updated_by BIGINT
);

-- ---------------------------------------------------------------- FIN-10 / FIN-20 tersambung ke PO, GR, surat jalan

ALTER TABLE fin.ap_invoice ADD COLUMN po_id BIGINT REFERENCES prc.po(id);
ALTER TABLE fin.ap_invoice_line
    ADD COLUMN po_line_id      BIGINT REFERENCES prc.po_line(id),
    ADD COLUMN po_price        NUMERIC(19,4),
    ADD COLUMN price_var_pct   NUMERIC(9,4);
ALTER TABLE fin.ar_invoice ADD COLUMN delivery_id BIGINT REFERENCES scm.delivery(id);
ALTER TABLE fin.ar_invoice ADD COLUMN source_type VARCHAR(8) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE fin.ar_invoice ADD COLUMN tax_reported BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE fin.ap_invoice ADD COLUMN tax_credited BOOLEAN NOT NULL DEFAULT FALSE;
